export const bindings = {
  title: 'Подключённые сервисы',
  empty: 'Сервисы пока не подключены',
  emptyText: 'Подключите сервис по договору — заявки по технике будут уходить ему напрямую.',
  addButton: 'Подключить сервис',
  catalogLink: 'Исполнители',

  statusLabel: {
    pending: 'Ожидает подтверждения',
    confirmed: 'Обслуживание подтверждено',
    rejected: 'Отклонено',
    revoked: 'Связь прекращена',
  },
  statusTag: {
    pending: 'Ожидает подтверждения сервисом',
    confirmed: 'Подтверждено сервисом',
    rejected: 'Сервис не подтвердил',
    revoked: 'Связь прекращена',
  },
  confirmedOn: (date: string) => `Подтверждено сервисом ${date}`,
  contactOnlyBadge: 'Мой контакт',
  contactOnlySubtitle: 'мой контакт',
  contactOnlyHint: 'Платформа не подтверждала обслуживание и не доставляет обращения этой компании',
  guarantorLabel: 'Гарантирующая сторона',
  providerLabel: 'Обслуживающая компания',
  invitationItem: (index: number, description?: string | null) =>
    description ? `Позиция ${index + 1} из приглашения: ${description}` : `Позиция ${index + 1} из приглашения`,
  basisLabel: {
    warranty: 'Гарантия',
    service_contract: 'Договор обслуживания',
    preferred_provider: 'Постоянный сервис',
  },
  guarantorKind: {
    manufacturer: 'Производитель',
    seller: 'Продавец',
    service_org: 'Сервисная организация',
  },
  contractShort: (number: string) => `Договор № ${number}`,
  contractNo: (number: string) => `№ ${number}`,
  until: (date: string) => `до ${date}`,
  detailStatus: 'Статус',
  detailContract: 'Договор',
  detailEquipment: 'Техника',
  detailBasis: 'Основание',
  detailTerm: 'Срок',
  revokeButton: 'Отозвать привязку',
  revokeReasonLabel: 'Причина отзыва',
  revokeConfirm: 'Отозвать',

  warrantyRow: 'Гарантия',
  warrantyBy: (name: string) => `Гарантирует: ${name}`,
  warrantyTitle: 'Гарантия',
  warrantyGuarantor: 'Гарантирует',
  warrantyServicer: 'Обслуживает',
  warrantySource: 'Источник',
  warrantyTerm: 'Срок',
  warrantyNoTerm: 'Не указан',
  warrantyAuthority: 'Полномочия производителя',
  warrantyAuthorityNone: (brand: string | null) =>
    brand ? `Нет подтверждения от ${brand}` : 'Нет подтверждения от производителя',
  warrantyAuthorityOk: (name: string) => `Подтверждены оператором: ${name}`,
  warrantyAuthorityDemo: 'демонстрационная проверка',
  warrantyAuthorityUntil: (date: string) => `полномочия до ${date}`,
  warrantyConfirmedByProvider: 'Подтвердил сервис',
  warrantyConfirmedByCustomer: 'Подтвердили вы',
  warrantyNote:
    'Относится ли конкретная поломка к гарантии, решает сервис по каждой заявке. При смене мастера гарантия не переходит.',
  warrantyNone: 'Гарантийных сведений нет',
  warrantyNoneText: 'По этой технике нет подтверждённой привязки с гарантией.',

  connectTitle: 'Подключить сервис',
  connectQuestion: 'Как подключить сервис?',
  wayInvite: 'По приглашению от сервиса',
  wayInviteText: 'Сервис пришлёт ссылку на договор и технику',
  wayRequest: 'По номеру договора',
  wayRequestText: 'Сервис проверит запрос по своим данным',
  wayContact: 'Сохранить контакт мастера',
  wayContactText: 'Без отправки заявок через приложение',
  connectNote: 'Подключённый сервис получает заявки только по технике из договора.',
  done: 'Готово',

  acceptLinkTitle: 'По приглашению',
  acceptLinkHint: 'Вставьте ссылку на приглашение, которую передал сервис через известный договорной контакт',
  acceptLinkLabel: 'Ссылка или код приглашения',
  acceptLinkOpen: 'Открыть приглашение',

  requestTitle: 'По номеру договора',
  requestHeading: 'Привязать свой сервис',
  requestLead: 'Сервис подтвердит договор. До этого заявки пойдут как обычные.',
  requestProviderLabel: 'Сервис',
  requestProviderPlaceholder: 'Название или ИНН',
  requestProviderHint: 'Введите не меньше 3 букв названия или ИНН целиком',
  requestProviderNotFound: 'Сервис не найден. Проверьте название или ИНН.',
  requestContractLabel: 'Номер договора',
  requestContractPlaceholder: 'Например, СО-2291',
  requestContractHint: 'Номер договора — реквизит поиска, не пароль и не секрет доступа',
  requestBasisLabel: 'Основание',
  requestBasis: {
    service_contract: 'Договор обслуживания',
    warranty: 'Гарантия',
    preferred_provider: 'Постоянный сервис',
  },
  requestEquipmentLabel: 'Техника',
  requestLimitNote: 'Можно отправить не больше 5 запросов за 15 минут.',
  requestAttemptsLeft: (left: number) => `Попыток осталось: ${left} из 5 за 15 минут.`,
  requestSubmit: 'Запросить подтверждение',
  requestSentTitle: 'Ждём подтверждения',
  requestSentText: (provider: string, contract: string) => `${provider} проверит договор ${contract}. Сообщим в MAX.`,
  requestSentStatus: 'Статус',
  requestSentStatusValue: 'На проверке у сервиса',
  requestSentBasis: 'Основание',
  requestSentPrivacy:
    'Мы не показываем, найден ли договор, — это защищает данные клиентов сервиса.',
  requestCancel: 'Отменить запрос',
  requestCancelConfirm: 'Отменить запрос?',
  requestCancelConfirmText: 'Сервис не получит запрос на подключение. Отправить новый можно в любой момент.',
  requiredLink: 'Вставьте ссылку или код приглашения',
  requiredProvider: 'Выберите сервис из списка',
  requiredContract: 'Укажите номер договора',
  requiredEquipment: 'Отметьте хотя бы одну технику',
  requiredContactName: 'Укажите имя или название',
  requiredContactEquipment: 'Выберите технику',
  requestCancelReason: 'Заказчик отменил запрос',
  rateLimitTitle: (minutes: number) => {
    const mod10 = minutes % 10;
    const mod100 = minutes % 100;
    const word =
      mod10 === 1 && mod100 !== 11
        ? 'минуту'
        : mod10 >= 2 && mod10 <= 4 && (mod100 < 12 || mod100 > 14)
          ? 'минуты'
          : 'минут';
    return `Попробуйте через ${minutes} ${word}`;
  },
  rateLimitText: 'Можно отправить не больше 5 запросов за 15 минут.',
  rateLimitOk: 'Понятно',

  contactTitle: 'Контакт мастера',
  contactNameLabel: 'Имя или название',
  contactPhoneLabel: 'Телефон',
  contactEquipmentLabel: 'Техника',
  contactSubmit: 'Сохранить контакт',
  contactSaved: 'Контакт сохранён',
  contactSavedText: 'Он появится в карточке техники. Заявки ему через приложение не отправляются.',
  contactHint: 'Обычный подрядчик без проверки платформой — это не гарантийная привязка',

  acceptTitle: 'Подключение',
  acceptOffer: (provider: string) => `Приглашение от ${provider}`,
  acceptLead: 'Сервис будет обслуживать вашу технику. Заявки по ней пойдут им напрямую.',
  acceptOfferText: 'Сверьте номер договора и перечень техники перед подключением.',
  acceptVerified: 'Проверенный сервис · реквизиты и представитель подтверждены',
  acceptVerifiedRequisites: 'Реквизиты сервиса подтверждены · представитель не проверен',
  acceptVerifiedRepresentative: 'Представитель сервиса подтверждён · реквизиты не проверены',
  acceptNotVerified: 'Реквизиты и представитель сервиса платформой не проверены',
  acceptDecline: 'Отклонить',
  acceptDeclineTitle: 'Отклонить приглашение?',
  acceptDeclineText: 'Сервис увидит, что вы отказались. Техника к нему не подключится.',
  acceptDeclineReasonLabel: 'Причина',
  acceptDeclineConfirm: 'Отклонить приглашение',
  acceptDeclined: 'Приглашение отклонено',
  acceptDeclinedText: (provider: string) => `${provider} получит уведомление. Технику можно подключить позже.`,
  acceptInvalid: 'Приглашение недействительно',
  acceptInvalidDescription: 'Ссылка устарела, отозвана или уже использована другой организацией.',
  acceptNotDisclosedDescription:
    'Условия договора видит только руководитель организации, которой адресовано приглашение. Выберите её и откройте ссылку снова.',
  acceptBasis: 'Основание',
  acceptTerm: 'Срок',
  acceptExpires: 'Приглашение действует до',
  acceptGuarantor: 'Гарантию даёт',
  acceptGuarantorHint: 'со слов сервиса',
  acceptGuarantorManufacturerHint: 'со слов сервиса, полномочия производителя не проверены',
  acceptGuarantorValue: (kind: string | null, name: string | null) =>
    [kind, name].filter(Boolean).join(': '),
  acceptItemsCaption: 'Техника',
  acceptMatchHint: 'Выберите технику для каждой позиции договора. Заводские номера должны совпадать.',
  acceptMatchAllHint: 'Сопоставьте все позиции, чтобы подключить сервис',
  acceptItemFallback: (n: number) => `Позиция ${n}`,
  acceptItemSerial: (serial: string) => `зав. № ${serial}`,
  acceptItemMatched: (title: string, place: string | null) => (place ? `Ваша: ${title} · ${place}` : `Ваша: ${title}`),
  acceptItemPick: 'Выберите свою технику',
  acceptItemButton: (item: string, state: string) => `${item}. ${state}`,
  acceptPickTitle: 'Какая это техника у вас?',
  acceptPickList: (item: string) => `Ваша техника для позиции «${item}»`,
  acceptPickClear: 'Не сопоставлять',
  acceptSerialMismatchTitle: 'Заводской номер не совпадает',
  acceptSerialMismatch: (title: string) =>
    `Заводской номер выбранной техники не совпадает с позицией «${title}» — выберите другую или уточните данные у сервиса.`,
  acceptNoEquipment: 'Сначала добавьте технику, чтобы сопоставить её с позициями договора.',
  acceptAddEquipment: 'Добавить технику',
  acceptConfirm: 'Подключить',
  acceptSuccess: 'Сервис подключён',
  acceptSuccessText: (units: string, provider: string) => `${units} техники теперь обслуживает ${provider}.`,

  incomingTitle: 'Привязки клиентов',
  clientsTitle: 'Клиенты',
  requestsCaption: 'Запросы по договору',
  requestTag: 'Проверьте по своей CRM',
  requestSubtitle: (contract: string, equipment: string) => `Договор ${contract} · ${equipment}`,
  incomingEmpty: 'Новых запросов нет',
  incomingConfirm: 'Подтвердить',
  incomingReject: 'Отклонить',
  incomingRejectReasonLabel: 'Причина отказа',
  incomingOnlyDeclared: 'Видно только заявленное — истории оборудования у вас пока нет',
  confirmedTitle: 'Подтверждённые',
  confirmedEmpty: 'Подтверждённых привязок пока нет',
  clientsNote: 'Подтверждайте только клиентов, которых знаете по договору.',
  invitationsCaption: 'Приглашения',
  invitationTitle: (contract: string) => `Договор ${contract}`,
  invitationSubtitle: (units: string, until: string) => `${units} · до ${until}`,
  invitationUnits: (n: number) => {
    const mod10 = n % 10;
    const mod100 = n % 100;
    if (mod10 === 1 && mod100 !== 11) return `${n} единица`;
    if (mod10 >= 2 && mod10 <= 4 && (mod100 < 12 || mod100 > 14)) return `${n} единицы`;
    return `${n} единиц`;
  },
  invitationTag: {
    active: 'Не принято',
    used: 'Принято',
    revoked: 'Отозвано',
    expired: 'Истекло',
    declined: 'Отклонено',
  },
  invitationDeclineReason: (reason: string) => `Причина: «${reason}»`,
  invitationDeclinedAt: 'Отклонено',
  invitationRevoke: 'Отозвать приглашение',
  invitationsAll: 'Все приглашения',

  invitationsTitle: 'Приглашения клиентов',
  invitationsEmpty: 'Приглашений пока нет',
  invitationsCreate: 'Создать приглашение',
  invitationsNewTitle: 'Новое приглашение',
  invitationsCreatedTitle: 'Приглашение создано',
  invitationsCustomerInn: 'ИНН заказчика',
  invitationsCustomerName: 'Название заказчика',
  invitationsContract: 'Номер договора',
  invitationsBasis: 'Основание',
  invitationsValidFrom: 'Действует с',
  invitationsValidUntil: 'Действует по',
  invitationsEquipmentPlaceholder: 'Например: холодильная витрина',
  invitationsItemsTitle: 'Техника по договору',
  invitationsItemsHint:
    'Перечислите позиции договора — клиент сопоставит каждую со своей карточкой техники. Серийный номер помогает избежать ошибки.',
  invitationsItemLabel: (n: number) => `Позиция ${n}`,
  invitationsItemDescription: 'Описание',
  invitationsItemModel: 'Модель',
  invitationsItemSerial: 'Серийный номер',
  invitationsItemAdd: 'Добавить позицию',
  invitationsItemRemove: 'Удалить позицию',
  invitationsItemsCount: (n: number) => `позиций: ${n}`,
  invitationsSubmit: 'Создать приглашение',
  invitationsLinkNotice: 'Полный токен показывается только сейчас. Передайте ссылку через известный договорной контакт клиента.',
  invitationsCopyReminder: 'Не отправляйте ссылку публично — только через контакт, указанный в договоре',
  invitationsState: {
    active: 'Активно',
    used: 'Использовано',
    revoked: 'Отозвано',
    expired: 'Истекло',
    declined: 'Отклонено заказчиком',
  },
} as const;
