import { urgencyText } from './requests';

export const offers = {
  title: 'Предложения исполнителей',
  empty: 'Предложений пока нет',
  empty24h: 'Исполнители ещё отвечают — обычно предложения приходят в течение суток',
  loadError: 'Не удалось загрузить предложения',

  visitWindow: 'Окно выезда',
  visitWindowUnknown: 'Время не указано',
  priceLabel: 'Стоимость выезда/диагностики',
  scopeLabel: 'Что входит',
  vatLabel: 'НДС',
  selectConfirmScheduled: 'Если исполнитель подтвердит, выезд будет согласован на это время и цену.',
  accessRequirementsLabel: 'Требования к доступу',
  commentLabel: 'Комментарий исполнителя',
  validUntilLabel: 'Действительно до',
  expiresIn: 'Осталось',
  expiredBadge: 'Срок истёк',
  withdrawnBadge: 'Отозвано исполнителем',
  selectedBadge: 'Выбрано',
  closedBadge: 'Закрыто',

  selectButton: 'Выбрать исполнителя',
  selectConfirmTitle: 'Выбрать это предложение?',
  selectConfirmDescription: 'Остальные предложения закроются для выбора. Платформа запросит подтверждение у исполнителя.',
  selectConfirmSubmit: 'Подтвердить выбор',
  selectError: 'Не удалось выбрать предложение',
  selectExpiredError: 'Срок этого предложения истёк — обновите список',
  offerNotCurrent: 'Исполнитель обновил предложение — проверьте актуальные условия и подтвердите выбор ещё раз.',

  awaitingConfirmationTitle: 'Ждём подтверждения исполнителя',
  awaitingConfirmationDescription:
    'Исполнитель должен подтвердить назначение. Если он откажется или не ответит в срок, резерв освободится и можно будет выбрать другое предложение.',

  providerFewReviews: 'Мало отзывов',
  providerNoRating: 'Отзывов пока нет',

  listTitle: 'Предложения',
  sortLabel: 'Сортировка предложений',
  sortTime: 'По времени',
  sortPrice: 'По цене',
  sortNote: 'Порядок — по времени выезда. Рейтинг и реклама на него не влияют.',
  validUntilShort: (time: string) => `до ${time}`,
  validUntilLong: (time: string) => `действует до ${time}`,
  priceAfterInspection: 'цена неизвестна',
  ratingTag: (rating: string, orgs: string) => `★ ${rating} · ${orgs}`,
  orgForms: ['организация', 'организации', 'организаций'] as const,
  providerFallback: 'Исполнитель',
  whenLabel: 'Когда',
  onSiteLabel: 'Нужно на объекте',
  validUntilRow: 'Действует до',
  profileRow: 'Профиль исполнителя',
  askQuestionRow: 'Задать вопрос',
  question: {
    title: 'Вопрос исполнителя',
    beforeChoice: 'до выбора',
    privateTitle: 'Видите только вы и этот исполнитель',
    privateText: 'Адрес и телефон ему не откроются до выбора.',
    fieldLabel: 'Ответ',
    placeholder: 'Ответить исполнителю',
  },
  selectFor: (price: string) => `Выбрать за ${price}`,
  select: 'Выбрать',
  afterSelectNote: 'После выбора исполнитель подтвердит заявку. Тогда ему откроются адрес и телефон.',
  priceUnknownTitle: 'Цена неизвестна',
  priceUnknownCaption: 'Мастер назовёт её после осмотра',
  notConsentTitle: 'Выбор — не согласие на цену',
  notConsentText: 'Мастер пришлёт стоимость, выезд состоится только после вашего подтверждения.',
  defaultScope: 'Выезд и диагностика',
  notFound: 'Предложение не найдено.',
  inactiveTitle: 'Предложение недоступно',
  backToOffers: 'К предложениям',
  reviewForms: ['отзыв', 'отзыва', 'отзывов'] as const,
  chooseUntil: (time: string) => `Выберите до ${time}, потом они истекут`,
  noneSelectable: 'Сейчас выбрать нечего: сроки истекли или предложения отозваны',
  selectNamed: (name: string) => `Выбрать ${name}`,
  moreAbout: (name: string) => `Подробнее: ${name}`,
  providerLabel: 'Исполнитель',
  priceCaption: 'Выезд и диагностика; ремонт — отдельным согласованием',
  toRequest: 'К заявке',
} as const;

export const approvals = {
  homeEmpty: 'Сейчас ничего не ждёт вашего решения',
  kindDraftApproval: 'Черновик сотрудника ждёт публикации',
  kindVisitProposal: 'Условия выезда ждут согласования',
  kindRepairQuote: 'Смета ремонта ждёт согласования',
  kindOffers: 'Есть предложения исполнителей',
  kindCompletion: 'Исполнитель сообщил о результате',
  kindCancellationDisputed: 'Исполнитель ответил на запрос отмены',

  visitTitle: 'Согласование выезда',
  quoteTitle: 'Согласование ремонта',
  versionLabel: 'Версия',
  windowLabel: 'Окно выезда',
  workDescriptionLabel: 'Описание работ',
  priceLabel: 'Стоимость',
  vatLabel: 'НДС',
  zeroCostReasonLabel: 'Основание бесплатного обслуживания',
  accessRequirementsLabel: 'Требования к доступу',
  commentLabel: 'Комментарий исполнителя',
  validUntilLabel: 'Действительно до',
  expiredNotice: 'Срок этой версии истёк — исполнитель должен прислать новую',
  supersededNotice: 'Появилась более новая версия условий',
  respondedNotice: 'Ответ по этой версии уже дан',

  approveButton: 'Согласовать',
  rejectButton: 'Отклонить',
  rejectReasonLabel: 'Комментарий (необязательно)',
  approveError: 'Не удалось согласовать',
  rejectError: 'Не удалось отклонить',
  priceUnknownNotice: 'Стоимость ещё не указана исполнителем — согласовать нельзя, дождитесь уточнения',

  versionConflictTitle: 'Условия изменились',
  versionConflictDescription: 'Пока вы читали экран, появилась новая версия — вот актуальные условия, подтвердите ещё раз.',
  versionConflictReload: 'Показать актуальные условия',
  visitNotFound: 'Условия выезда не найдены.',

  visitOfferCaption: (version: number) => `Предложение выезда · версия ${version}`,
  visitOfferCaptionShort: 'Предложение выезда',
  whenLabel: 'Когда',
  masterLabel: 'Мастер',
  replyUntilLabel: 'Ответить до',
  reasonLabel: 'Причина',
  repairLaterNote: 'Стоимость ремонта мастер пришлёт после диагностики — её вы согласуете отдельно.',
  approveWithPrice: (price: string) => `Согласовать ${price}`,
  replacedTitle: (current: number, previous: number) =>
    `Версия ${current} заменила версию ${previous}`,
  replacedText: 'Прежнее согласие к новым условиям не применяется.',
  changedSubtitle: (provider: string) => `${provider} изменил предложение`,
  managerDecidesTitle: 'Решение принимает руководитель',
  managerDecidesText: 'Руководитель получил уведомление.',
  rejectSheetTitle: 'Отклонить предложение выезда?',
  rejectSheetText: 'Сервис увидит ваш ответ и сможет прислать новые условия.',
  rejectConfirm: 'Отклонить предложение',
  expiredTitle: 'Срок ответа истёк',
  staleLinkTitle: 'Эти условия уже заменены',
  staleLinkText: (opened: number, current: number) =>
    `Вы открыли уведомление о версии ${opened}. Сервис прислал версию ${current} — прежнюю согласовать нельзя.`,
  showNewTerms: 'Посмотреть новые условия',
  quoteNotFound: 'Смета не найдена.',

  quoteHeading: 'Цена ремонта',
  quoteSubtitle: (provider: string, version: number) => `${provider} · после диагностики · версия ${version}`,
  quoteCaption: (version: number, until: string) => `Итого, версия ${version} · ответить до ${until}`,
  quoteWorksCaption: 'Работы',
  quoteItemsLabel: 'Позиции сметы',
  quoteVisitApprovedNote: (price: string) => `Выезд и диагностика (${price}) согласованы отдельно.`,
  warrantyCaption: 'Доплата за ремонт',
  basisLabel: 'Основание',
  worksLabel: 'Работы',
  deadlineLabel: 'Срок',
  untilDate: (date: string) => `до ${date}`,
  warrantyNote: 'Гарантийность случая определил сервис. Приложение это не проверяет.',
  approveRepair: 'Согласовать ремонт',
  rejectTitle: 'Отклонить',
  rejectHeading: 'Почему отказываетесь?',
  rejectSubtitle: 'Сервис увидит причину и сможет прислать новую версию.',
  rejectReasonsLabel: 'Причина отклонения',
  rejectReasons: ['Слишком дорого', 'Не подходит время', 'Нужен другой состав работ'],
  rejectCommentLabel: 'Комментарий',

  visitHeading: 'Согласуйте выезд',
  visitHeadingEmployee: 'Предложение выезда',
  scopeLabel: 'Что входит',
  totalLabel: 'Итого',
  notPaymentNote: 'Согласование цены — не оплата: платите сервису напрямую.',
  quoteApprovedTitle: 'Согласовано',
  quoteRejectedTitle: 'Отказ',
  quoteApprovedText: 'Цена согласована. Мастер приступит к ремонту.',
  quoteRejectedText: 'Вы отказались от ремонта по этой цене.',
  decisionFinalNote: 'Решение не отменяется: если условия изменятся, исполнитель пришлёт новую версию.',
  warrantyTerms: (terms: string) => `Гарантия на работы: ${terms} (со слов исполнителя).`,
  validUntilSentence: (until: string) => `Предложение действует до ${until}.`,
  rejectQuoteButton: 'Отказаться',
  rejectQuoteConfirm: 'Отказаться',
  priceChangedTitle: 'Цена изменилась',
  priceChangedText: (provider: string) =>
    `Пока вы смотрели, ${provider} обновил предложение. Проверьте новую версию перед согласованием.`,
  priceWas: (price: string) => `Было ${price}`,
  priceNow: (price: string) => `Стало ${price}`,
  showNewVersion: 'Посмотреть новую версию',
} as const;

export const requestsCard = {
  updateDetails: {
    title: 'Изменить условия',
    hint: 'Уточните заявку перед новым маршрутом. Отправленная ранее версия не переписывается — правка сохранится в истории.',
    symptomLabel: 'Описание неисправности',
    urgencyLabel: 'Срочность',
    publicCardTitle: 'Карточка для исполнителей',
    districtLabel: 'Район',
    publishedDescriptionLabel: 'Описание для карточки',
    submit: 'Сохранить условия',
    error: 'Не удалось сохранить условия',
    noChanges: 'Условия не изменились — поправьте описание, срочность или район.',
    symptomRequired: 'Опишите, что случилось, — без описания исполнитель не поймёт задачу.',
    notAvailable: 'Условия меняются только у заявки, которой нужно ваше решение.',
    urgencyOption: urgencyText as Record<string, string>,
  },

  card: {
    backToList: 'К списку заявок',
    acceptedAt: (provider: string, time: string) => `${provider} принял в ${time}`,
    messagesRow: 'Переписка',
    historyRow: 'История',
    detailsRow: 'Описание и фото',
    detailsCaption: 'Заявка',
    providerCaption: 'Исполнитель',
    urgencyTitle: 'Срочность',
    equipmentTitle: 'Оборудование',
    locationTitle: 'Точка',
    symptomsTitle: 'Симптомы',
    errorCodeTitle: 'Код ошибки',
    providerTitle: 'Исполнитель',
    providerUnknown: 'Исполнитель ещё не выбран',
    assignmentStatusLabel: 'Статус назначения',
    fieldWorkerTitle: 'Мастер на выезде',
    fieldWorkerStatedByCompany: 'указано компанией',
    visitWindowTitle: 'Окно выезда',
    visitWindowUnknown: 'Время выезда пока не согласовано',
    warrantyTitle: 'Гарантийность',
    warrantyStatedByProvider: 'Решение исполнителя, не платформы',
    warrantyDecision: {
      not_stated: 'Не указано',
      warranty: 'Гарантийный случай',
      not_warranty: 'Не гарантийный случай',
      undetermined: 'Пока не определено',
    },
    photosIncompleteTag: 'Отправлено с неполными фото',
    disputedTag: 'Отмена решена в одностороннем порядке',

    historyTitle: 'История',
    historyShow: 'Показать историю',
    historyHide: 'Скрыть историю',
    historyEmpty: 'Событий пока нет',
    historyEvents: {
      RequestDrafted: 'Черновик создан',
      RequestDraftUpdated: 'Черновик изменён',
      RequestSubmittedForApproval: 'Отправлена на согласование',
      RequestReturnedToDraft: 'Возвращена в черновик',
      RequestSubmittedToOwnService: 'Отправлена своему сервису',
      SearchPublished: 'Запущен внешний поиск',
      SearchFoundNoProviders: 'Подходящих исполнителей не нашлось',
      SearchExpired: 'Срок поиска истёк',
      SearchStopped: 'Подбор исполнителя остановлен',
      RequestCancelled: 'Заявка отменена',
      AssignmentAccepted: 'Исполнитель принял заявку',
      AssignmentDeclined: 'Исполнитель отказался',
      AssignmentRevoked: 'Назначение отозвано',
      AssignmentWithdrawn: 'Исполнитель отказался от заявки',
      AssignmentConfirmed: 'Исполнитель подтвердил назначение',
      AssignmentExpired: 'Срок подтверждения назначения истёк',
      OwnServiceReminded: 'Сервису отправлено напоминание',
      OfferSubmitted: 'Получено предложение',
      OfferWithdrawn: 'Предложение отозвано',
      OfferExpired: 'Срок предложения истёк',
      OfferSelected: 'Выбрано предложение',
      VisitProposed: 'Предложен выезд',
      VisitProposalSuperseded: 'Предложение выезда обновлено',
      VisitAgreed: 'Выезд согласован',
      VisitProposalRejected: 'Выезд отклонён',
      VisitProposalExpired: 'Срок предложения выезда истёк',
      RepairQuoteCreated: 'Получена смета',
      RepairQuoteApproved: 'Смета согласована',
      RepairQuoteRejected: 'Смета отклонена',
      RepairQuoteExpired: 'Срок сметы истёк',
      CancellationRequested: 'Запрошена отмена',
      CancellationDisputed: 'Исполнитель оспорил отмену',
      CancellationWithdrawn: 'Запрос отмены отозван',
      CancellationForced: 'Отмена завершена без согласия исполнителя',
      WorkStarted: 'Работы начаты',
      CompletionReported: 'Исполнитель сообщил о завершении',
      CompletionRejected: 'Результат не принят',
      CompletionReminderSent: 'Напоминание о подтверждении результата',
      RequestClosed: 'Заявка закрыта',
      RequestDetailsUpdated: 'Условия заявки изменены',
      LinkedRequestCreated: 'Создана связанная заявка',
      MessageCreated: 'Новое сообщение',
      ExternalReferenceLinked: 'Связана с CRM',
      WarrantyDecisionStated: 'Указано решение по гарантии',
      FieldWorkerAssigned: 'Назначен выездной специалист',
      FieldWorkerEnRoute: 'Мастер выехал',
      'completion.reminder': 'Напоминание о подтверждении результата',
      'request.auto_closed': 'Заявка закрыта автоматически — результат не подтверждён в срок',
    } as Record<string, string>,

    messagesTitle: 'Переписка',
    messagesEmpty: 'Сообщений пока нет',
    messagesShow: 'Открыть переписку',
    messagesHide: 'Скрыть переписку',
    messageAttachPhoto: 'Приложить фото',
    messagePhotosPending: 'Фото к сообщению',
    messagesThreadWith: 'Переписка с',
    messagePlaceholder: 'Написать сообщение…',
    messageSend: 'Отправить',
    messageSendError: 'Сообщение не отправлено',

    attachmentsTitle: 'Вложения',
    attachmentsEmpty: 'Вложений нет',
    attachmentStateQuarantined: 'Проверяется',
    attachmentStateRejected: 'Отклонено',
    attachmentOpen: 'Открыть',
    attachmentDelete: 'Удалить',
    attachmentLoadError: 'Не удалось загрузить файл',

    actionsTitle: 'Действия',
    actionRevokeAssignment: 'Отозвать назначение',
    actionRevokeAssignmentConfirm: 'Отозвать неподтверждённое назначение и выбрать другой путь?',
    actionGoExternalSearch: 'Перейти к внешнему поиску',
    actionUpdateDetails: 'Изменить условия',
    actionPublish: 'Опубликовать во внешнем поиске',
    actionSubmitOwnService: 'Отправить своему сервису',
    actionReturnToDraft: 'Вернуть на доработку',
    actionReturnToDraftCommentLabel: 'Что нужно исправить',
    actionCancel: 'Отменить заявку',
    actionConfirmCompletion: 'Подтвердить результат',
    actionRejectCompletion: 'Есть проблема',
    actionRejectCompletionReasonLabel: 'Что осталось не так',
    actionCreateFollowup: 'Создать связанную заявку',
    actionOpenOffers: 'Сравнить предложения',
    actionOpenVisitApproval: 'Согласовать выезд',
    actionOpenQuoteApproval: 'Согласовать ремонт',
    actionNoAccessEmployee: 'Согласование и отмена — действия руководителя. Вы можете следить за статусом и перепиской.',
    actionComplainNoShow: 'Жалоба на неявку',

    cancelTargetLabel: 'Что нужно',
    cancelTargetCancelRequest: 'Отменить заявку полностью',
    cancelTargetChangeProvider: 'Сменить исполнителя',
    cancelReasonLabel: 'Причина отмены',
    cancelBeforeAcceptNotice: 'Исполнитель ещё не принял заявку — отмена произойдёт сразу.',
    cancelAfterAcceptNotice: 'Исполнитель уже принял заявку — отправляется запрос отмены, исполнитель должен ответить.',
    cancelPendingTitle: 'Запрос отмены отправлен',
    cancelStatusLabel: 'Статус',
    cancelPendingDescription: 'Ждём ответа исполнителя — согласия или несогласия.',
    cancelProviderResponse: 'Ответ исполнителя',
    cancelDisputedTitle: 'Исполнитель не согласен с отменой',
    cancelDisputedDescription: 'Состояние осталось нерешённым. Можно отозвать запрос или, по истечении срока ожидания, прекратить работу в одностороннем порядке.',
    cancelSilentDescription: 'Исполнитель не ответил в срок. Можно отозвать запрос или прекратить работу в одностороннем порядке.',
    cancelWithdraw: 'Отозвать запрос отмены',
    cancelForceClose: 'Прекратить в одностороннем порядке',
    cancelForceCloseLocked: 'Доступно после истечения срока ожидания ответа исполнителя',
    cancelForceCloseLockedUntil: (deadline: string) =>
      `Доступно после истечения срока ожидания ответа исполнителя (до ${deadline})`,
    cancelSubmit: 'Отправить запрос отмены',

    noAccess403: 'Сервер не разрешил это действие — данные на экране уже обновлены.',
    versionConflict: 'Данные заявки изменились, пока вы читали экран — показаны актуальные сведения.',

    publishedAt: (time: string) => `опубликовано в ${time}`,
    chosenProvider: (name: string) => `Выбран исполнитель ${name}`,
    photosRow: 'Фото',
    approvalTitle: 'Нужно ваше решение',
    approvalTextMarketplace:
      'Сотрудник предлагает найти внешнего исполнителя. Перед публикацией вы увидите, что узнают мастера.',
    approvalTextOwnService: 'Сотрудник предлагает отправить заявку своему сервису.',
    approvalEmployeeText: (approver: string | null | undefined) =>
      `${approver?.trim() || 'Руководитель'} проверит, что увидят исполнители, и откроет поиск.`,
    reviewAndPublish: 'Проверить и опубликовать',
    returnToEmployee: 'Вернуть сотруднику',
    returnSheetTitle: 'Вернуть заявку сотруднику?',
    returnSheetText: 'Сотрудник увидит комментарий и сможет исправить черновик.',
    waitingProviderTitle: 'Ждём ответа сервиса',
    waitingProviderDelivered: 'Заявка доставлена, но её пока никто не принял.',
    waitingProviderSent: 'Заявка отправлена, но её пока никто не принял.',
    timelineSent: 'Отправлено',
    timelineDelivered: 'Доставлено в CRM',
    timelineAccepted: 'Принято сервисом',
    timelineWaiting: 'ожидаем',
    timelineDeliveredApp: 'Доставлено в приложение исполнителя',
    timelineRetrying: 'повторяем',
    timelineFailed: 'не доставлено',
    deliveryFailedTitle: 'CRM сервиса недоступна',
    deliveryRetryingText: (time: string | null) =>
      `Заявка сохранена. Повторяем доставку автоматически${time ? `, последняя попытка в ${time}` : ''}.`,
    deliveryFailedText: (time: string | null) =>
      `Заявка сохранена, но доставить её в CRM не удалось${time ? ` (последняя попытка в ${time})` : ''}. Позвоните в сервис или отзовите заявку.`,
    callProvider: 'Позвонить в сервис',
    callProviderNamed: (provider: string) => `Позвонить в ${provider}`,
    revokeAndFindOther: 'Отозвать и найти другого',
    revokeConfirmText: 'Сервис больше не увидит заявку. Затем выберите другого исполнителя.',
    writeToProvider: 'Написать сервису',
    searchingTitle: 'Ищем исполнителя',
    searchingText: (matched: string, offers: string | null) =>
      `Заявку видят ${matched} вашей категории и района. ${offers ? `Уже есть ${offers}.` : 'Сообщим о каждом предложении.'}`,
    matchedForms: ['исполнитель', 'исполнителя', 'исполнителей'] as const,
    offerForms: ['предложение', 'предложения', 'предложений'] as const,
    compareOffers: 'Сравнить предложения',
    changeConditions: 'Изменить условия',
    unpublish: 'Снять с публикации',
    unpublishConfirm: 'Снять заявку с публикации?',
    unpublishConfirmText:
      'Поиск остановится, предложения закроются. Заявку можно будет изменить и опубликовать снова.',
    editSearchConfirm: 'Изменить условия поиска?',
    editSearchConfirmText: 'Для правки поиск остановится. После изменений опубликуйте заявку снова.',
    noProvidersTitle: 'Рядом нет исполнителей',
    noProvidersText:
      'Никто не работает с такой техникой в вашем районе. Попробуйте расширить срок или район.',
    changeDistrict: 'Изменить район',
    saveAndWait: 'Сохранить и ждать',
    reserveExpiredTitle: 'Исполнитель не подтвердил',
    reserveExpiredText: (provider: string, active: string | null) =>
      `Резерв исполнителя ${provider} истёк. Поиск снова открыт${active ? `, ещё действует: ${active}` : ''}.`,
    chooseAnotherOffer: 'Выбрать другое предложение',
    awaitingConfirmText: (time: string) =>
      `Резерв действует до ${time}. Остальные предложения пока не закрыты.`,
    cancelChoice: 'Отменить выбор',
    cancelChoiceConfirm: 'Отменить выбор исполнителя?',
    cancelChoiceConfirmText: 'Резерв снимется, подбор остановится — заявка вернётся к вам на решение.',
    acceptedText: 'Исполнитель принял заявку — ждём предложения времени и стоимости выезда.',
    visitPriceRow: 'Выезд и диагностика',
    repairRow: 'Ремонт',
    repairAfterDiagnostics: 'цена после диагностики',
    repairAwaiting: 'ждёт согласования',
    approvedOn: (date: string) => `Согласовано ${date}`,
    cancelVisit: 'Отменить выезд',
    inProgressTitle: 'Мастер работает',
    inProgressText: (who: string, time: string | null) =>
      `${who} ${time ? `начал работу в ${time}` : 'работает над заявкой'}. Когда закончит, вы получите отчёт.`,
    reportTitle: 'Мастер закончил ремонт',
    reportNote: 'Оплата — напрямую сервису, не через приложение.',
    reportPhotosLabel: 'Фото отчёта',
    reportPhotoBefore: 'До',
    reportPhotoAfter: 'После',
    reportPhotoAlt: (slot: string, number: number, index: number) =>
      `Фото «${slot}» к отчёту по заявке Р-${number}, ${index}`,
    allWorks: 'Принять работу',
    remarkTitle: 'Замечание',
    remarkHeading: 'Что не так?',
    remarkSubtitle: (who: string) => `Сообщим мастеру, заявка вернётся ему в работу: ${who}.`,
    remarkLabel: 'Описание',
    remarkPhotos: 'Фото к замечанию',
    remarkPhotoTooLarge: (name: string) => `${name}: файл больше 10 МБ. Выберите другой или снимите заново.`,
    remarkNote: 'Отзыв о работе можно оставить в любой момент, подтверждать ремонт для этого не нужно.',
    returnToWork: 'Вернуть в работу',
    declinedTitle: (provider: string) => `${provider} отказался`,
    declinedText: (provider: string | null, reason: string | null) =>
      reason
        ? `${provider ?? 'Сервис'}: «${reason}». Заявку можно отправить другим исполнителям, данные сохранятся.`
        : 'Заявку можно отправить другим исполнителям, данные сохранятся.',
    withdrawnTitle: (provider: string) => `${provider} отказался от работы`,
    declinedTitleNoName: 'Сервис отказал',
    withdrawnTitleNoName: 'Исполнитель отказался от работы',
    expiredAssignmentTitle: 'Исполнитель не ответил вовремя',
    revokedTitle: 'Вы отозвали заявку у исполнителя',
    searchStoppedTitle: 'Подбор остановлен',
    noAutoSearchNote: 'Внешний поиск не запустится сам: вы решите, что увидят исполнители.',
    findProvider: 'Найти исполнителя',
    cancellationPendingTitle: 'Отмена на согласовании',
    cancellationPendingText:
      'Вы запросили отмену. Исполнитель уже принял заявку, поэтому ему нужно подтвердить. Если мастер уже выехал, сервис может попросить оплатить выезд.',
    cancellationTargetRow: 'Цель',
    cancellationReasonRow: 'Причина',
    cancellationRequestedRow: 'Запрошено',
    cancellationTarget: { cancel_request: 'Отменить заявку', change_provider: 'Сменить исполнителя' } as Record<
      string,
      string
    >,
    withdrawRequest: 'Не отменять',
    withdrawRequestConfirm: 'Отозвать запрос отмены?',
    withdrawRequestConfirmText: 'Заявка продолжится на прежних условиях.',
    closedTitle: 'Работа принята',
    closedText: (when: string) => `Вы подтвердили результат ${when}. Оцените мастера — это помогает другим заказчикам.`,
    autoClosedTitle: 'Заявка закрыта',
    autoClosedText: (when: string) => `Результат не подтвердили в срок — заявка закрыта автоматически ${when}.`,
    totalApproved: 'Итого согласовано',
    brokeAgain: 'Сломалось снова — новая заявка',
    leaveReview: 'Оценить мастера',
    cancelledTitle: 'Заявка отменена',
    cancelledText: (when: string, beforeAccept: boolean) =>
      `Отменена ${when}${beforeAccept ? ', исполнитель её ещё не принял' : ''}.`,
    cancelledTextNoDate: 'Заявка больше не в работе.',
    createNewRequest: 'Создать новую заявку',
    atTime: (date: string, time: string) => `${date} в ${time}`,
    today: 'Сегодня',
    tomorrow: 'Завтра',

    done: 'Готово',
    rating: (value: string) => `★ ${value}`,
    ratingWithCount: (value: string, count: string) => `★ ${value} (${count})`,
    collapse: 'Свернуть',
    expand: 'Подробнее',
    expandWithPhotos: (count: number) => `Показать полностью и ${count} фото`,
    historyAll: (count: number) => `Вся история · ${count}`,
    justNow: 'только что',
    minutesAgo: (value: string) => `${value} назад`,
    minuteForms: ['минуту', 'минуты', 'минут'] as const,
    hourForms: ['час', 'часа', 'часов'] as const,
    pricesLabel: 'Цены',
    visitApproved: 'Согласовано',
    repairOnSite: 'Ремонт оценят на месте',
    repairAwaitingManager: 'ждёт решения руководителя',
    timelineSentTo: (provider: string) => `Отправлено ${provider}`,
    silentTitle: (provider: string) => `${provider} молчит`,
    waitingProviderDeliveredAgo: (ago: string) => `Заявка доставлена ${ago}, но её пока никто не принял.`,
    waitingProviderSentAgo: (ago: string) => `Заявка отправлена ${ago}, но её пока никто не принял.`,
    waitOrFindOther: 'Можно подождать или найти другого исполнителя.',
    remindAt: (time: string) => `Напомним вам в ${time}, если сервис не ответит`,
    remindSoon: 'Напомним вам, если сервис не ответит',
    wait: 'Подождать',
    findOther: 'Найти другого',
    cancelShort: 'Отменить',
    changeTerm: 'Изменить срок',
    editRequest: 'Изменить заявку',
    writeToMaster: 'Написать мастеру',
    waitingAnswer: 'Ждём ответа',
    enRouteTitle: 'Мастер едет',
    scheduledTitle: 'Выезд согласован',
    enRouteText: (who: string, time: string) => `${who} отметил выезд в ${time}.`,
    scheduledText: (who: string) => `${who} приедет в согласованное окно.`,
    quoteWaitingText: (who: string) => `${who} прислал цену ремонта. Согласуйте её, чтобы работа продолжилась.`,
    quoteWaitingEmployee: 'Мастер прислал цену ремонта — её согласует руководитель.',
    reportText: 'Мастер отметил завершение. Проверьте, что техника работает, и подтвердите результат.',
    reportDone: 'Что сделано',
    reportSum: 'Сумма',
    reportSumValue: (total: string) => `${total} · как согласовано`,
    reportLabel: 'Отчёт мастера',
    remarkSend: 'Отправить',
    remarkIssuesLabel: 'Что не так',
    remarkIssues: ['Снова не работает', 'Шумит', 'Течёт', 'Цена выше согласованной'],
    remarkSentTitle: 'Отправили мастеру',
    remarkSentText: (who: string) => `${who} ответит в переписке по заявке. Заявка вернулась в работу.`,
    crmAuthor: (provider: string) => `${provider} · CRM`,
    questionAnswer: 'Ответить',
  },

  messages: {
    title: 'Переписка',
    you: 'Вы',
    author: {
      provider_membership: 'Исполнитель',
      customer_membership: 'Заказчик',
      integration_client: 'CRM сервиса',
    } as Record<string, string>,
    photoCount: (n: number) => `${n} фото`,
    notDelivered: 'Не доставлено',
    retry: 'повторить',
    fieldLabel: 'Сообщение',
    placeholderCustomer: 'Написать мастеру',
    closedNote: 'Заявка завершена — переписка доступна только для чтения.',
    today: 'Сегодня',
    yesterday: 'Вчера',
    quickLabel: 'Быстрые ответы',
    quickReplies: ['Когда будете?', 'Жду', 'Позвоните мне'],
    clarificationTitle: 'Сервис уточняет',
    answerSentTitle: 'Ответ отправлен',
    clarificationQuick: ['Да', 'Нет', 'Позвоните мне'],
    answerLabel: 'Ваш ответ',
    answerPlaceholder: 'Напишите ответ сервису',
    answer: 'Ответить',
    addToAnswer: 'Дополнить',
    addToAnswerLabel: 'Добавить к ответу',
    openChat: 'Вся переписка',
    deliveredToCrm: 'Доставлено в CRM',
    sentAt: (time: string) => `Отправлено в ${time}`,
    loadEarlier: 'Показать более ранние',
    photoTooLarge: (name: string) => `${name}: файл больше 10 МБ. Выберите другой или снимите заново.`,
  },
  history: {
    title: 'История',
    visitProposed: (version: number) => `Предложен выезд, версия ${version}`,
    visitSuperseded: (version: number) => `Версия ${version} заменила версию ${version - 1}`,
    quoteCreated: (version: number) => `Смета ремонта, версия ${version}`,
  },

  cancel: {
    title: 'Отмена',
    heading: 'Что вы хотите сделать?',
    optionsLabel: 'Что вы хотите сделать',
    cancelRequest: 'Отменить заявку',
    cancelRequestHint: 'Ремонт больше не нужен',
    changeProvider: 'Сменить исполнителя',
    changeProviderHint: 'Заявка останется, другого исполнителя выберете вы',
    reasonLabel: 'Причина',
    reasonPlaceholder: 'Причина отмены',
    acceptedTitle: 'Исполнитель уже принял заявку',
    acceptedText: 'Отмена вступит в силу после его подтверждения. Новые данные заявки ему больше не придут.',
    notAcceptedTitle: 'Исполнитель ещё не принял заявку',
    notAcceptedText: 'Отмена произойдёт сразу, подтверждение исполнителя не нужно.',
    submitRequest: 'Отправить запрос',
    submitNow: 'Отменить сейчас',
    pendingHeading: 'Запрос отмены',
  },
} as const;
