export const equipment = {
  title: 'Техника',
  newEquipment: 'Новая техника',
  addEquipment: 'Добавить технику',
  editEquipment: 'Изменить данные',
  editTitle: 'Изменить технику',
  locationFilter: 'Точка',
  allLocations: 'Все',
  allLocationsChip: 'Все точки',
  emptyTitle: 'Техники пока нет',
  emptyText: 'Добавьте оборудование: заявки по нему создаются в два нажатия.',
  emptyEmployeeTitle: 'Техники пока нет',
  emptyEmployeeText: 'Технику добавляет руководитель организации.',
  emptyLocation: 'На этой точке пока нет техники',
  noLocationsTitle: 'Сначала добавьте точку',
  noLocationsText: 'Техника учитывается по точкам — адрес точки подставится в заявку.',
  addLocation: 'Добавить точку',
  listNewRequest: 'Новая заявка',
  listCard: 'Карточка',
  listStatus: {
    activeRequest: (state: string, number: string) => `${state} · ${number}`,
  },
  serviceSummary: {
    warranty: (guarantor: string, until: string | null, stated: boolean) =>
      `Гарантия: ${guarantor}${stated ? ' (со слов сервиса)' : ''}${until ? ` · до ${until}` : ''}`,
    contract: (name: string, until: string | null) =>
      until ? `${name} · договор до ${until}` : `${name} · договор`,
    preferred: (name: string) => `${name} · постоянный сервис`,
    pending: (name: string | null) =>
      name ? `${name} · ждёт подтверждения сервиса` : 'Ждёт подтверждения сервиса',
    contact: (name: string) => `Мой контакт: ${name}`,
    none: 'Сервис не привязан',
  },

  location: 'Точка',
  locationPlaceholder: 'Выберите точку',
  category: 'Категория',
  categoryPlaceholder: 'Выберите категорию',
  brand: 'Бренд',
  model: 'Модель',
  serialNumber: 'Заводской номер',
  notes: 'Примечания',
  optionalPlaceholder: 'Необязательно',
  notSpecifiedSerial: 'Не указан',

  typeLabel: 'Тип',
  typeShort: {
    commercial_display_fridge: 'Холодильная витрина',
    refrigerator_cabinet: 'Холодильник',
    chest_freezer: 'Морозильный ларь',
    ice_maker: 'Льдогенератор',
    bar_fridge: 'Холодильник для напитков',
    refrigeration_unit: 'Холодильный блок',
    split_system_cold_room: 'Морозильная камера',
    fridge: 'Холодильник',
    coffee: 'Кофемашина',
  } as Record<string, string>,
  otherType: 'Другой тип',
  otherTypeLabel: 'Какой тип',
  otherTypePlaceholder: 'Например, пароконвектомат',
  otherTypeNote: (name: string) => `Тип: ${name}`,
  nameplateLabel: 'Шильдик',
  nameplateTake: 'Сфотографировать',
  nameplateTakeHint: 'Табличка с моделью и номером, обычно сзади',
  nameplateAdded: 'Фото добавлено',
  nameplateAddedHint: 'Видят только вы и ваш сервис',
  nameplateRemove: 'Убрать',
  brandPlaceholder: 'Carboma',
  modelPlaceholder: 'F16',
  serialPlaceholder: 'Необязательно, есть на шильдике',
  addHint: 'Тип, бренд и модель обязательны, фото шильдика по желанию',
  addSubmit: 'Добавить',

  photosCaption: 'Фото',
  photoSlots: ['Общий вид', 'Шильдик'] as const,
  photoAddSlot: (slot: string) => `Добавить фото: ${slot}`,
  photoTooLarge: (name: string) => `Файл «${name}» больше 10 МБ — выберите фото поменьше.`,
  photoFileSlot: (slot: string) => `Файл фото: ${slot}`,
  photoRemoveSlot: (slot: string) => `Убрать фото: ${slot}`,
  photoAdd: 'Добавить фото',
  photoFile: 'Файл фото',
  photoTileAdd: 'Добавить',
  photoPrivacyNote: 'Шильдик и серийный номер не попадут во внешний поиск без вашего выбора.',
  photosEmpty: 'Фото пока нет',
  photosUploading: 'Загружаем…',
  photosUploadError: 'Не удалось загрузить фото',
  photosAfterCreateError: 'Техника сохранена, но фото не загрузилось. Добавьте его ещё раз на карточке.',
  photoAlt: (title: string, index: number) => `Фото техники ${title}, ${index}`,

  serialShort: (serial: string) => `зав. № ${serial}`,
  tabsLabel: 'Разделы карточки',
  tabs: {
    service: 'Сервис',
    history: 'История',
    specs: 'Данные',
  },
  serviceCaption: 'Обслуживание',
  serviceState: {
    confirmed: 'Подтверждённый сервис',
    pending: 'Ждёт подтверждения сервиса',
    contact: 'Мой контакт',
  },
  serviceBasis: 'Основание',
  serviceValid: 'Действует',
  serviceWarranty: 'Гарантия',
  serviceWarrantyValue: (guarantor: string, until: string | null) =>
    until ? `${guarantor} · до ${until}` : guarantor,
  serviceWarrantyLink: (value: string) => `Гарантия: ${value}`,
  servicePhone: 'Телефон',
  noServiceTitle: 'Отправить заявку через приложение нельзя',
  noServiceContactText:
    'Этот мастер не подключён. Позвоните ему или найдите исполнителя через поиск.',
  noServiceText:
    'Сервис для этой техники не подключён. Подключите его по договору или найдите исполнителя через поиск.',
  connectService: 'Подключить сервис',
  findProvider: 'Найти исполнителя',
  newRequest: 'Новая заявка',
  requestToService: (provider: string) => `Заявка в ${provider}`,
  menuServices: 'Подключённые сервисы',
  requestsCaption: 'Заявки',
  historyEmpty: 'Заявок по этой технике ещё не было',
  historyRow: (number: string, title: string) => `${number}: ${title}`,
  historyToday: 'сегодня',
  historyYesterday: 'вчера',
  historySub: (state: string, number: string) => `${state} · ${number}`,
  specs: {
    category: 'Тип',
    brand: 'Бренд',
    model: 'Модель',
    serial: 'Заводской номер',
    location: 'Точка',
    created: 'Добавлена',
    nameplate: 'Фото шильдика',
    nameplateYes: 'Есть',
    nameplateNo: 'Нет',
  },
} as const;
