export const integration = {
  title: 'Интеграция',
  apiKeysTab: 'Ключи',
  subscriptionsTab: 'Подписки',
  deliveriesTab: 'Доставки',
  helpTab: 'Справка',

  apiKeysEmpty: 'Ключей пока нет',
  createKey: 'Создать ключ',
  keyNameLabel: 'Название ключа',
  keyNamePlaceholder: 'Например: CRM продакшн',
  keyScopesLabel: 'Разрешения (scope)',
  keyCreated: 'Ключ создан',
  keyShownOnce: 'Сохраните его в CRM. Потом увидеть ключ будет нельзя, только выпустить новый.',
  keyPrefix: 'Префикс',
  keyStatus: {
    active: 'Активен',
    revoked: 'Отозван',
  },
  keyLastUsed: 'Последнее использование',
  keyCreatedAt: 'Создан',
  keyRotate: 'Ротация',
  keyRotateConfirm: 'Выпустить новый ключ взамен текущего? Прежний перестанет действовать.',
  keyRevoke: 'Отозвать',
  keyRevokeConfirm: 'Отозвать ключ без возможности восстановления?',

  scopeDescriptions: {
    'requests:read': 'Чтение заявок, адресованных вашей компании',
    'requests:write':
      'Действия по заявкам: принять, отклонить, предложить условия, сообщить результат',
    'marketplace:read': 'Чтение доступных заявок внешнего поиска',
    'marketplace:write': 'Отклики на заявки внешнего поиска',
    'equipment:read': 'Чтение оборудования с подтверждённой привязкой',
    'service_bindings:read': 'Чтение привязок вашей компании',
    'service_bindings:write': 'Создание приглашений на привязку и ответы на запросы',
    'reviews:read': 'Чтение отзывов о вашей компании',
    'reviews:write': 'Ответы на отзывы',
    'webhooks:manage': 'Управление подписками на вебхуки',
    'events:read': 'Восстановление событий через /events',
  },

  subscriptionsEmpty: 'Подписок на вебхуки пока нет',
  subscriptionStatus: {
    active: 'Активна',
    disabled: 'Отключена',
  },

  deliveriesEmpty: 'Доставок пока нет',
  redeliver: 'Повторить доставку',
  deliveryState: {
    queued: 'В очереди',
    delivered: 'Доставлено',
    retrying: 'Ждёт повтора',
    failed: 'Не удалось',
    blocked: 'Заблокировано',
  },
  deliveryInFlight: 'В работе',
  deliveryAttempts: 'Попытки',
  deliveryLastStatus: 'Код ответа',
  deliveryLastError: 'Ошибка',
  deliveryNextAttempt: 'Следующая попытка',

  helpTitle: 'Справка для интегратора',
  helpSignature:
    'Подпись HMAC-SHA256 отдельным секретом подписки рассчитывается от строки timestamp + "." + raw_body. Заголовки: X-Event-ID, X-Delivery-ID, X-Timestamp, X-Signature.',
  helpIdempotency:
    'Мутации поддерживают заголовок Idempotency-Key: повтор с тем же телом возвращает прежний результат, с другим телом — 409.',
  helpRecovery:
    'Доставка — как минимум один раз, события могут прийти не по порядку. После исчерпания попыток используйте GET /events с курсором, чтобы восстановить пропущенные события (хранятся 30 дней).',
  statusRow: 'Статус',
  connected: 'Подключена',
  notConnected: 'Не подключена',
  apiKeysRow: 'API-ключи',
  webhooksRow: 'Вебхуки',
  logRow: 'Журнал доставки',
  errorsBannerTitle: 'Есть ошибки доставки',
  errorsBannerText: (count: number, since: string, httpStatus: number | null) =>
    `Не доставлено в CRM: ${count} с ${since}.${httpStatus ? ` CRM отвечает ${httpStatus}.` : ''}`,
  redeliverError: 'Не удалось повторить доставку',
  deliverySubtitle: (time: string, httpStatus: number | null) =>
    httpStatus ? `${time} · HTTP ${httpStatus}` : time,
  deliveryInFlightTag: 'в работе',
  deliveryLastAttempt: 'Последняя попытка',
  deliveryId: 'Delivery ID',
  issuedTitle: 'API-ключ',
  issuedClose: 'Скопировал, закрыть',
  keyCreatedOnce: 'Ключ показывается один раз',
  keyRights: 'Права',
  keyBindingsRight: 'Привязки клиентов',
  scopeGroup: {
    requests: 'заявки',
    marketplace: 'внешний поиск',
    equipment: 'оборудование',
    service_bindings: 'привязки',
    reviews: 'отзывы',
    webhooks: 'вебхуки',
    events: 'события',
  } as Record<string, string>,

  crmConnected: 'CRM подключена',
  crmNotConnected: 'CRM не подключена',
  lastEvent: (when: string) => `Последнее событие ${when}`,
  onlyMaxText: 'Заявки приходят только в MAX',
  webhookRow: 'Вебхук',
  webhookNone: 'Не настроен',
  eventsDayRow: 'Событий за сутки',
  eventsDayValue: (total: number, failed: number) => `${total} · ошибок ${failed}`,
  apiKeyRow: 'API-ключ',
  keyMask: (prefix: string) => `${prefix}••••`,
  keyNone: 'Нет активного',
  keyScopesTitle: (name: string | null) => (name ? `Права ключа «${name}»` : 'Права ключа'),
  scopesImmutableNote:
    'Права выпущенного ключа не меняются. Нужны другие — выпустите новый ключ и отзовите прежний.',
  keyWarning: {
    service_bindings_write_shared: {
      title: 'Привязки — отдельным ключом',
      text: 'В этом ключе права на привязки техники вместе с правами на заявки. Выпустите для привязок отдельный ключ, а этот отзовите.',
    },
  } as Record<string, { title: string; text: string } | undefined>,
  scopeConflictError:
    'Право создавать привязки техники выдаётся отдельным ключом — без прав на заявки и отклики.',
  scopeTitle: {
    'requests:read': 'Получать заявки',
    'requests:write': 'Обрабатывать заявки',
    'marketplace:read': 'Видеть заявки внешнего поиска',
    'marketplace:write': 'Откликаться на заявки',
    'equipment:read': 'Видеть технику клиентов',
    'service_bindings:read': 'Видеть привязки техники',
    'service_bindings:write': 'Создавать привязки техники',
    'reviews:read': 'Читать отзывы',
    'reviews:write': 'Отвечать на отзывы',
    'webhooks:manage': 'Управлять вебхуками',
    'events:read': 'Восстанавливать события',
  } as Record<string, string>,
  keyKindLabel: 'Для чего ключ',
  keyKindRequests: 'Заявки',
  keyKindBindings: 'Привязки техники',
  keyKindRequestsHint:
    'Заявки, отклики, сообщения, отзывы и события. Права на привязки техники выпускаются отдельным ключом.',
  keyKindBindingsHint:
    'Только привязки техники по договору — отдельно от заявок, как требует порядок работы с ключами.',
  copied: 'Скопировано',
  copyFailed: 'Скопировать не получилось — выделите значение в поле и скопируйте вручную.',
  leaveUncopiedTitle: 'Закрыть без копирования?',
  leaveUncopiedText: 'Значение показывается один раз. После закрытия посмотреть его будет нельзя — только выпустить новое.',
  leaveUncopiedConfirm: 'Закрыть',
  copyKey: 'Скопировать ключ',

  connectCrm: 'Подключить CRM',
  disableIntegration: 'Отключить интеграцию',
  enableIntegration: 'Включить интеграцию',
  disableIntegrationConfirm:
    'Отключить доставку событий в CRM? Ключи API продолжат действовать — отозвать их можно в разделе «API-ключи».',
  disableConfirmLabel: 'Отключить',
  webhookDisabledValue: (url: string) => `${url} · отключён`,
  webhookUrlLabel: 'Адрес вебхука',
  webhookUrlPlaceholder: 'https://crm.example.ru/max',
  webhookUrlHint: 'Только https. Сюда придут события по заявкам.',
  webhookKeyLabel: 'Ключ интеграции',
  webhookKeyHint: 'Активных ключей несколько — выберите, к какому привязать подписку.',
  webhookNeedsKey: 'Подписка привязывается к ключу API. Сначала выпустите ключ.',
  noActiveKeyError: 'Сначала выпустите ключ API — подписка привязывается к нему.',
  chooseKeyError: 'Выберите ключ интеграции.',
  subscriptionEvents: 'События',
  subscriptionEnable: 'Включить',
  subscriptionDisable: 'Отключить',
  secretTitle: 'Секрет подписи',
  secretOnceTitle: 'Секрет показывается один раз',
  secretOnceText:
    'Сохраните его в CRM: по нему CRM проверяет подпись событий. Потом увидеть секрет будет нельзя, только выпустить новый.',
  copySecret: 'Скопировать секрет',
  rotateSecret: 'Новый секрет подписи',
  rotateSecretConfirm:
    'Выпустить новый секрет подписи? Прежний перестанет действовать — обновите его в CRM.',
  rotateSecretConfirmLabel: 'Выпустить',
} as const;
