export const operator = {
  navLabel: 'Оператор',
  homeTitle: 'Очереди оператора',
  homeSubtitle: 'Решения окончательны для версии дела и сохраняются с основанием.',
  queuesCaption: 'Очереди',
  decisionCaption: 'Решение',
  decisionLabel: 'Вариант решения',
  caseTag: 'На проверке',
  innShort: (inn: string) => `ИНН ${inn}`,
  rating: (value: number) => `${value}/5`,
  fraudTag: 'Накрутка?',
  fraudCaption: 'Пометка накрутки',
  warrantyBrandsAll: 'все бренды',
  bindingTitle: (customer: string, provider: string) => `${customer} → ${provider}`,
  attachmentMeta: (visibility: string, mime: string) => `${visibility} · ${mime}`,
  attachmentsWarningTitle: 'Перед одобрением',
  appealTag: 'Обжалование',
  caseTitle: 'Дело',
  verificationQueueTitle: 'Проверка профилей и представителей',
  providerProfilesTitle: 'Профили исполнителей',
  profilesTab: 'Профили',
  appealsTab: 'Обжалования',
  profilesViewLabel: 'Что показать',
  appealsEmpty: 'Обжалований на рассмотрении нет',
  appealSheetTitle: (name: string) => `Обжалование: ${name}`,
  appealTextCaption: 'Основания исполнителя',
  appealFiledStatus: (status: string, reason: string | null) =>
    `Статус при подаче: ${status}${reason ? ` · причина: ${reason}` : ''}`,
  appealUphold: 'Удовлетворить',
  appealDecline: 'Отклонить',
  appealReasonLabel: 'Основание решения (обязательно)',
  appealReinstateNote: 'Решение не меняет статус профиля: при удовлетворении восстановите профиль во вкладке «Профили».',

  queueEmpty: 'Очередь пуста',
  genericError: 'Не удалось загрузить очередь',

  caseSubjectLabel: 'Что проверяем',
  caseOrganizationLabel: 'Организация',
  caseInnLabel: 'ИНН',
  caseEvidenceLabel: 'Заявленные сведения',
  caseEvidenceNote: 'Закрытые доказательства — во внутренней очереди, заявителю не показываются',

  decisionApprove: 'Одобрить',
  decisionNeedsInfo: 'Уточнить',
  decisionReject: 'Отклонить',
  decisionReasonLabel: 'Основание решения (обязательно)',
  decisionReasonRequired: 'Без основания решение не отправить',
  decisionSourceLabel: 'Источник проверки (обязательно)',
  decisionNotEvidenceHint:
    'Не основание само по себе: скан, печать, логотип, селфи и фотография паспорта. Нужен независимый канал — обратный звонок по официальному контакту, подтверждение уже известного партнёра.',
  decisionConfirm: 'Решение окончательное для этой версии дела. Подтвердить?',
  decisionSubmit: 'Отправить решение',
  decisionSuccess: 'Решение сохранено, дело ушло из очереди',
  decisionError: 'Не удалось сохранить решение',

  profileStatusActive: 'Допущен',
  profileStatusSuspended: 'Приостановлен',
  profileSuspendAction: 'Приостановить',
  profileReinstateAction: 'Восстановить',
  profileReasonLabel: 'Причина (обязательно)',
  profileActionError: 'Не удалось выполнить действие',

  accessDeniedDescription: 'Открыт только пользователям с платформенной ролью оператора.',

  warrantyQueueTitle: 'Гарантийные полномочия',
  warrantyEmpty: 'Полномочий пока не выдано',
  warrantyIssueTitle: 'Выдать полномочие',
  warrantyProviderLabel: 'Исполнитель (id организации)',
  warrantyGuarantorKindLabel: 'Гарантирующая сторона',
  warrantyGuarantorKind: {
    manufacturer: 'Производитель',
    seller: 'Продавец',
    service_org: 'Сервисная организация',
  },
  warrantyGuarantorNameLabel: 'Название гаранта',
  warrantyBrandsLabel: 'Бренды через запятую',
  warrantyCategoryLabel: 'Категория оборудования (id, необязательно)',
  warrantyCityLabel: 'Город (id, необязательно)',
  warrantyValidUntilLabel: 'Действует до',
  warrantySourceLabel: 'Источник проверки (обязательно)',
  warrantyReasonLabel: 'Основание выдачи (обязательно)',
  warrantyIssueSubmit: 'Выдать',
  warrantyIssueError: 'Не удалось выдать полномочие',
  warrantyRevoke: 'Отозвать',
  warrantyRevokeReasonLabel: 'Причина отзыва (обязательно)',
  warrantyStatus: {
    pending: 'Ожидает',
    active: 'Действует',
    expired: 'Истекло',
    revoked: 'Отозвано',
  },

  bindingsQueueTitle: 'Привязки заказчик—исполнитель',
  bindingsEmpty: 'Привязок пока нет',
  bindingsRevoke: 'Отозвать привязку',
  bindingsRevokeReasonLabel: 'Причина отзыва (обязательно)',
  bindingsBasisLabel: 'Основание',
  bindingsContractLabel: 'Номер договора',

  attachmentsQueueTitle: 'Изображения на модерации',
  attachmentsEmpty: 'Очередь пуста',
  attachmentsSensitiveWarning: 'Проверьте, нет ли на фото шильдика, документов или персональных данных, прежде чем одобрить',
  attachmentsApprove: 'Одобрить',
  attachmentsReject: 'Отклонить',
  attachmentsRejectReasonLabel: 'Причина отклонения (обязательно)',
  attachmentsLoadError: 'Не удалось загрузить изображение',
  attachmentsImageAlt: 'Изображение на модерации',
  complaintSubjectLabel: {
    provider_profile: 'Профиль исполнителя',
    review: 'Отзыв',
    attachment: 'Фотография',
    service_binding: 'Привязка',
    no_show: 'Неявка',
  } as Record<string, string>,
  verificationSubjectLabel: {
    requisites: 'Реквизиты организации',
    representative: 'Представитель исполнителя',
    customer_representative: 'Представитель заказчика',
  } as Record<string, string>,

  reviewsQueueTitle: 'Отзывы на модерации',
  reviewsEmpty: 'Очередь пуста',
  reviewsFraudSignalsTitle: 'Сигналы накрутки',
  reviewsFraudSignalsHint: 'Сигнал — повод проверить, не доказательство',
  reviewsFraudSignalsNone: 'Сигналов нет',
  reviewsPublish: 'Опубликовать',
  reviewsReject: 'Отклонить',
  reviewsRemove: 'Удалить опубликованный',
  reviewsDecisionReasonLabel: 'Причина (обязательна для отклонения и удаления)',
  reviewsMarkFraud: 'Пометить накрутку',
  reviewsUnmarkFraud: 'Снять пометку накрутки',
  reviewsFraudReasonLabel: 'Комментарий (обязательно)',
  reviewsFraudNotice: 'Отзыв останется видимым — пометка лишь исключает его из числа при подсчёте рейтинга',

  casesQueueTitle: 'Жалобы и обжалования',
  casesEmpty: 'Дел пока нет',
  casesSubjectFilterAll: 'Все типы',
  casesEvidenceTitle: 'Заявленное',
  casesDecidePublish: 'Подтвердить',
  casesDecideReject: 'Отклонить',
  casesDecideRemove: 'Удовлетворить (удалить/снять)',
  casesReasonLabel: 'Причина решения (обязательна для отклонения и удаления)',
  casesAppealLabel: 'Обжалование',

  confirmYes: 'Подтвердить',
} as const;
