import { roleLower } from './onboarding';

const providerVerification = {
  scene: {
    draft: {
      title: 'Профиль не отправлен',
      text: 'Заполните анкету и отправьте её на проверку. До неё заявки не приходят.',
    },
    pending_review: {
      title: 'Проверяем профиль',
      text: 'Обычно 1–3 рабочих дня. Пока можно заполнить галерею и территорию.',
    },
    needs_information: {
      title: 'Нужны данные',
      text: 'Без подтверждения полномочий не можем допустить профиль к заявкам.',
    },
    active: {
      title: 'Профиль проверен',
      text: 'Теперь вам приходят заявки по выбранным категориям и территории.',
    },
    suspended: {
      title: 'Профиль приостановлен',
      text: 'Новые заявки не приходят. Причина — ниже.',
    },
    rejected: {
      title: 'Профиль отклонён',
      text: 'Заявки не приходят. Решение можно обжаловать в профиле.',
    },
  } as Record<string, { title: string; text: string }>,
  stepsLabel: 'Шаги проверки',
  requisitesCompany: 'Реквизиты компании',
  requisitesSelf: 'Реквизиты',
  representative: 'Полномочия представителя',
  categories: 'Категории работ',
  approvedAt: (date: string) => `Подтверждено ${date}`,
  approved: 'Подтверждено',
  demo: 'демонстрационная проверка',
  checking: 'Проверяет оператор',
  needsInfo: 'Нужны сведения',
  rejected: 'Отклонено',
  notStarted: 'После отправки профиля',
  categoriesAfter: 'После проверки полномочий',
  categoriesEmpty: 'Категории не выбраны',
  toRequests: 'К заявкам',
  fillProfile: 'Заполнить профиль',
  toProfile: 'К профилю',
  evidenceCaption: 'Документы для оператора',
} as const;

export const organization = {
  title: 'Организация',
  innLine: (inn: string) => `ИНН ${inn}`,
  innMissing: 'ИНН не указан',
  youAre: Object.fromEntries(
    Object.entries(roleLower).map(([role, label]) => [role, `вы ${label}`]),
  ) as Record<string, string>,
  addLocation: 'Добавить',
  invitationSent: 'Приглашение отправлено',
  invitationWaiting: (roleAndPlaces: string, until: string) =>
    `${roleAndPlaces} · ждём принятия до ${until}`,
  verificationCaption: 'Проверка',
  requisitesTitle: 'Реквизиты',
  requisitesTag: {
    verified: 'Проверены',
    pending: 'На проверке',
    needs_information: 'Нужны уточнения',
    rejected: 'Отклонены',
    unverified: 'Не проверены',
  } as Record<string, string>,
  representativeTitle: 'Проверка представителя',
  representativeHint: 'Нужна для подтверждённых договоров и отзывов',
  representativeTag: {
    verified: 'Пройдена',
    pending: 'На проверке',
    needs_information: 'Нужны уточнения',
    rejected: 'Отклонена',
    unverified: 'Не пройдена',
  } as Record<string, string>,
  staffTitle: 'Сотрудники',
  staffSubtitle: (role: string, places: string) => `${role} · ${places}`,
  allLocations: 'все точки',
  noLocations: 'точки не выбраны',
  invitationsCaption: 'Приглашения',
  invitationTitle: (role: string, places: string) => `${role} · ${places}`,
  inviteExpires: (date: string) => `Действует до ${date}`,
  inviteTag: {
    active: 'Не принято',
    used: 'Принято',
    revoked: 'Отозвано',
    expired: 'Истекло',
  } as Record<string, string>,
  inviteTitle: 'Пригласить',
  roleCaption: 'Роль',
  roleHint: {
    customer_employee: 'Заявки своих точек',
    customer_manager: 'Все заявки, цены, выбор исполнителя',
    provider_dispatcher: 'Заявки, выезды и работы',
    provider_admin: 'Профиль, сотрудники и интеграция',
  } as Record<string, string>,
  inviteHeading: 'Кого приглашаем',
  inviteSubtitle:
    'Сотрудник откроет ссылку в MAX. Доступ откроется после вашего подтверждения — или сразу, если указать его ID в MAX.',
  recipientCaption: 'Кому',
  recipientNameLabel: 'Имя сотрудника',
  recipientNameHint: 'Для сверки: при подтверждении покажем его рядом с именем из MAX',
  recipientIdLabel: 'ID пользователя в MAX',
  recipientIdHint:
    'Если знаете. Тогда ссылку примет только этот человек и доступ откроется без подтверждения',
  recipientRow: 'Кому',
  accessRow: 'Доступ',
  accessNamed: 'Сразу — только указанному пользователю MAX',
  accessOnApproval: 'После вашего подтверждения',
  inviteNote:
    'Ссылка одноразовая и действует ограниченное время — точный срок покажем после создания.',
  inviteSend: 'Отправить ссылку в MAX',
  inviteShareText: 'Приглашение в организацию',
  inviteCopiedForChat: 'Скопировано — вставьте в чат',
  inviteCopyWebapp: 'Скопировать ссылку',
  inviteCopyBot: 'Скопировать ссылку на бота',
  inviteSecretNote:
    'Не публикуйте ссылку в общих чатах: принять её может любой, к кому она попадёт. Перед подтверждением сверьте имя.',
  inviteNamedNote: 'Ссылку примет только указанный пользователь MAX. Для других она не сработает.',
  inviteLocationsRequired: 'Выберите хотя бы одну точку',
  createLink: 'Создать ссылку',
  inviteCreatedText: (date: string) =>
    `Ссылка действует до ${date}. Отправьте её сотруднику в MAX.`,
  inviteDone: 'Готово',
  inviteRevokeTitle: 'Отозвать приглашение?',
  inviteRevokeText: 'Ссылка перестанет работать.',
  memberPendingTag: 'Ждёт подтверждения',
  approveTitle: (name: string) => `Подтвердить: ${name}?`,
  approveText: 'Сотрудник получит доступ к заявкам организации.',
  approveCheck: 'Убедитесь, что это тот, кого вы приглашали: ссылку могли переслать.',
  approveNameInMax: 'Имя в MAX',
  approveExpectedName: 'Кого приглашали',
  approveAcceptedAt: 'Приглашение принято',
  memberPendingSince: (date: string) => `Приглашение принято ${date}`,
  reject: 'Отклонить',
  memberRevoke: 'Исключить',
  memberRevokeTitle: (name: string) => `Исключить: ${name}?`,
  memberRevokeText:
    'Доступ к заявкам, фото и переписке организации закроется со следующего действия. Вернуть сотрудника можно только новым приглашением.',
  profileEditTitle: 'Профиль организации',
  participationTitle: { provider: 'Стать исполнителем', customer: 'Стать заказчиком' },
  otherCaption: 'Ещё',
  staffTab: 'Сотрудники',
  invitationsTab: 'Приглашения',
  inviteButton: 'Пригласить сотрудника',
  role: 'Роль',
  locationsAccess: 'Доступные точки',
  editLocations: 'Изменить точки',
  inviteCreated: 'Приглашение создано',
  inviteLinkWebapp: 'Ссылка на мини-приложение',
  inviteLinkBot: 'Ссылка на бота',
  inviteExpiresAt: 'Действует до',
  noStaff: 'В организации пока нет сотрудников',
  noInvitations: 'Приглашений пока нет',
  membershipPending: 'Ожидает подтверждения',
  approve: 'Подтвердить',
  profileTitle: 'Профиль организации',
  innLabel: 'ИНН',
  contactLabel: 'Контакт',
  emailLabel: 'Эл. почта',
  profileEdit: 'Изменить профиль',
  profileSaveError: 'Не удалось сохранить профиль организации',
  contactNameLabel: 'Контактное лицо',
  innLockedHint: 'ИНН проверенной организации меняется только через оператора платформы',
  becomeProvider: 'Стать исполнителем',
  becomeCustomer: 'Стать заказчиком',
  participationProviderHint:
    'Организация начнёт принимать заявки как исполнитель. Для вас появится отдельная роль администратора исполнителя — переключаться между ролями можно в разделе «Организация».',
  participationCustomerHint:
    'Организация сможет оформлять заявки как заказчик. Для вас появится отдельная роль руководителя заказчика. Укажите первую точку обслуживания.',
  participationProviderKind: 'Форма работы',
  providerKindCompany: 'Компания',
  providerKindIndependent: 'Частный специалист',
  participationError: 'Не удалось добавить тип участия',
  complaintsLink: 'Мои жалобы',
  tabsLabel: 'Разделы организации',
  verification: providerVerification,
} as const;

export const locations = {
  title: 'Точки',
  newLocation: 'Новая точка',
  editLocation: 'Точка',
  empty: 'Точки ещё не добавлены',
  emptyText: 'Добавьте адрес, куда будет приезжать мастер.',
  add: 'Добавить точку',
  name: 'Название',
  city: 'Город',
  district: 'Район',
  address: 'Адрес',
  contactPhone: 'Контакт на месте',
  privacyNote: 'Адрес и телефон видит только ваш сервис и выбранный исполнитель.',
  customerOnly: 'Точки обслуживания есть только у заказчика.',
  equipmentForms: ['единица техники', 'единицы техники', 'единиц техники'] as const,
} as const;
