import { urgencyText } from './requests';

export const provider = {
  profileTitle: 'Профиль исполнителя',
  verificationTitle: 'Проверка',
  incomingStub: 'Здесь появятся обращения, адресованные вашей компании.',
  availableRequestsStub:
    'Здесь появятся обезличенные карточки внешнего поиска, подходящие вашей компании.',
  inWorkStub: 'Здесь появятся принятые заявки в работе.',
  staffAndInvitations: 'Сотрудники и приглашения',

  typeLabel: 'Тип исполнителя',
  typeCompany: 'Сервисная компания',
  typeIp: 'Индивидуальный предприниматель',
  typeSelfEmployed: 'Самозанятый мастер',
  innLabel: 'ИНН',
  innPlaceholder: '10 или 12 цифр',
  innInvalid: 'Проверьте ИНН — контрольные цифры не сходятся',
  innHintOrganization: 'ИНН организации (10 цифр)',
  innHintIndividual: 'ИНН физического лица (12 цифр)',

  sectionRequisites: '1. Тип и реквизиты',
  sectionContact: '2. Контакт для проверки',
  sectionCategories: '3. Категории оборудования',
  sectionArea: '4. Зона обслуживания',
  sectionBrands: '5. Ограничения по брендам',
  sectionTerms: '6. Условия выезда и документы',
  sectionDescription: '7. Описание',

  contactName: 'Ваше имя',
  representativePosition: 'Ваша должность',
  representativePositionPlaceholder: 'Например: директор',
  contactPhone: 'Рабочий телефон',
  contactEmail: 'Email',
  contactHint:
    'Оператор свяжется с вами для подтверждения полномочий представителя.',

  categoriesHint: 'Отметьте категории оборудования, которые обслуживает ваша компания.',
  categoriesEmpty: 'Категории не выбраны',

  areaHint:
    'Город целиком либо конкретные районы — отметьте обслуживаемые районы или оставьте город без районов, чтобы обслуживать его целиком.',
  areaWholeCity: 'Весь город',
  areaServeCity: 'Обслуживаем этот город',
  areaNoDistricts: 'Районы не выбраны — считается весь город',

  brandsHint:
    'Необязательно: ограничьте бренды по категории, если работаете не со всеми. Пустой список — без ограничений.',
  brandsPlaceholder: 'Бренды через запятую, например: Bosch, LG',

  canProvideDocuments: 'Можем предоставить документы по запросу заказчика',
  visitTerms: 'Условия выезда',
  visitPriceFromLabel: 'Выезд от, ₽',
  visitPriceFromHint: 'Минимальная стоимость выезда — её видят заказчики в профиле',
  visitPriceFrom: (price: string) => `от ${price}`,
  visitTermsPlaceholder: 'Стоимость и порядок выезда, сроки, зона бесплатного выезда…',
  description: 'Описание компании',
  descriptionPlaceholder: 'Расскажите о компании и опыте работы',
  specializationDisclaimer: 'Специализация указана со слов исполнителя и не проверяется платформой',

  submit: 'Отправить на проверку',
  saveDraft: 'Сохранить черновик',
  submitted: 'Профиль отправлен на проверку',

  acceptingHintAdmin: 'Приём новых заявок переключает администратор организации',
  acceptingLabel: 'Принимаю новые заявки',
  acceptingHintLocked: 'Приём заявок откроется после допуска профиля (статус «Допущен»)',
  acceptingHintUnlocked: 'Пока переключатель выключен, заявки вам не поступают',

  statusLabel: {
    draft: 'Черновик',
    pending_review: 'На проверке',
    needs_information: 'Нужны сведения',
    active: 'Допущен',
    suspended: 'Приостановлен',
    rejected: 'Отклонён',
  },
  statusWhatHappens: {
    draft: 'Профиль не отправлен на проверку — заявки не поступают.',
    pending_review: 'Оператор проверяет реквизиты и представителя. Заявки пока не поступают.',
    needs_information: 'Оператору нужны дополнительные сведения, чтобы продолжить проверку.',
    active: 'Профиль допущен. Заявки поступают, если включён приём новых заявок.',
    suspended: 'Профиль временно приостановлен — новые заявки не поступают.',
    rejected: 'Профиль отклонён — новые заявки не поступают.',
  },
  statusWhatToDo: {
    draft: 'Заполните обязательные разделы и нажмите «Отправить на проверку».',
    pending_review: 'Дополнительных действий не требуется — дождитесь решения оператора.',
    needs_information: 'Откройте раздел «Проверка» и передайте недостающие сведения текстом.',
    active: 'Держите профиль актуальным — территорию и условия выезда можно менять в любой момент.',
    suspended:
      'Причина и порядок обжалования указаны ниже. При вопросах обратитесь в поддержку платформы.',
    rejected:
      'Причина и порядок обжалования указаны ниже. При вопросах обратитесь в поддержку платформы.',
  },
  reasonLabel: 'Основание',
  beforeActiveNotice: 'До статуса «Допущен» заявки вашей компании не поступают.',
  requisitesLockedNotice:
    'Реквизиты уже проверены. Чтобы изменить их, потребуется повторная проверка.',
  profileLockedNotice: 'Профиль сейчас нельзя редактировать в этом статусе.',

  verificationCasesEmpty: 'Проверок пока не открыто',
  verificationCaseSubject: {
    requisites: 'Реквизиты',
    representative: 'Представитель',
    customer_representative: 'Представитель заказчика',
  },
  verificationDecision: {
    pending: 'На проверке',
    approved: 'Подтверждено',
    rejected: 'Отклонено',
    needs_information: 'Нужны сведения',
    revoked: 'Отозвано',
  },
  verificationNoteLabel: 'Сведения для оператора',
  verificationNotePlaceholder:
    'Опишите, что можете подтвердить: как связаться с представителем, ссылки на источники…',
  verificationSubmit: 'Отправить сведения',
  verificationSubmitted: 'Сведения отправлены оператору',
  verificationEvidenceTitle: 'Документы-доказательства',
  verificationEvidenceHint:
    'Выписка, доверенность, скан реквизитов — видит только оператор проверки.',
  verificationEvidenceUpload: 'Прикрепить документ',
  verificationEvidenceUploading: 'Загружаем…',
  verificationEvidenceUploadError: 'Не удалось загрузить документ',
  verificationEvidenceNoOpenCase: 'Документы можно приложить, когда открыто дело проверки',
  verificationEvidenceAlt: (index: number) => `Документ для проверки, ${index}`,
  demoBadgeLabel: 'Демонстрационная проверка',

  catalogTitle: 'Каталог исполнителей',
  catalogEmpty: 'По заданным фильтрам исполнители не найдены',
  catalogFilterCategory: 'Категория',
  catalogFilterCity: 'Город',
  catalogFilterDistrict: 'Район',
  catalogAnyCategory: 'Любая категория',
  catalogAnyCity: 'Любой город',
  catalogAnyDistrict: 'Любой район',
  acceptingBadge: 'Принимает заявки',
  notAcceptingBadge: 'Сейчас не принимает заявки',

  publicProfileVerificationTitle: 'Признаки проверки',
  publicProfileConfirmed: 'Подтверждено',
  publicProfileNotConfirmed: 'Не подтверждено',
  publicProfileSource: 'Источник',
  publicProfileCheckedAt: 'Дата проверки',
  publicProfileValidUntil: 'Действует до',
  publicProfileWarrantyTitle: 'Полномочия на гарантийное обслуживание',
  publicProfileWarrantyEmpty: 'Полномочий на гарантийное обслуживание не заявлено',
  publicProfileGalleryTitle: 'Галерея работ',
  publicProfileGalleryEmpty: 'Исполнитель ещё не добавил фотографии работ',
  publicProfileReviewsTitle: 'Отзывы',
  publicProfileReviewsEmpty: 'Отзывов пока нет',
  publicProfileRatingFew: 'Мало отзывов',
  publicProfileUniqueCustomers: 'уникальных заказчиков',
  publicProfileBrandRestrictions: 'Бренды по категориям',
  publicProfileNoRestrictions: 'Без ограничений по брендам',
  publicProfileAuthorConfirmed: 'Подтверждённый бизнес-клиент',
  publicProfileLoadMore: 'Показать ещё',
  publicProfilePhotoAlt: 'Фото к отзыву',
  publicProfileGalleryCaption: 'Загружено исполнителем',

  reviewsNavTitle: 'Отзывы',
  reviewsOwnTitle: 'Отзывы о компании',
  reviewsOwnEmpty: 'Опубликованных отзывов пока нет',
  reviewsCannotHideNotice:
    'Исполнитель не может скрыть или удалить отзыв. Отрицательная оценка сама по себе не основание для удаления — только нарушение (фейк, оскорбления, персональные данные) рассматривает оператор.',
  reviewsReplySubmit: 'Отправить ответ',
  reviewsReplyPlaceholder: 'Ответ виден всем — будьте по существу',
  reviewsReplySent: 'Ответ отправлен — тоже пройдёт модерацию',
  reviewsReplyError: 'Не удалось отправить ответ',
  reviewsReplyAlready: 'Вы уже ответили на этот отзыв',
  reviewsAppealButton: 'Оспорить отзыв',
  reviewsAppealDescription: 'Оспорить можно только опубликованный отзыв — заведёт дело у оператора',

  catalogHeader: 'Исполнители',
  catalogFiltersLabel: 'Фильтры каталога',
  catalogAllCategories: 'Все категории',
  catalogAllCities: 'Все города',
  catalogAllDistricts: 'Все районы',
  catalogKind: { company: 'Компания', independent_specialist: 'Мастер, самозанятый' },
  catalogNotAccepting: 'Не принимает',
  ratingTag: (value: string) => `★ ${value}`,
  ratingTagWithOrgs: (value: string, orgs: string) => `★ ${value} · ${orgs}`,
  orgForms: ['организация', 'организации', 'организаций'] as const,
  reviewForms: ['отзыв', 'отзыва', 'отзывов'] as const,
  photoForms: ['фото', 'фото', 'фото'] as const,
  publicProfileHeader: 'Исполнитель',
  publicProfileChecksCaption: 'Проверки платформы',
  publicProfileCheckSource: (source: string, date: string) => `${source} · ${date}`,
  publicProfileCheckValidUntil: (date: string) => `действует до ${date}`,
  publicProfileCheckDetails: 'Подробнее о проверке',
  publicProfileWarrantyRow: 'Гарантия производителя',
  publicProfileWarrantyRowBrands: (brands: string) => `Гарантия производителя · ${brands}`,
  publicProfileWarrantyNone: 'Не подтверждена',
  publicProfileWarrantyUntil: (guarantor: string, date: string) => `${guarantor} · до ${date}`,
  publicProfileWarrantyPending: 'На проверке',
  publicProfileReviewsRow: (rating: string) => `Отзывы · ★ ${rating}`,
  publicProfileReviewsSub: (orgs: string, reviews: string) => `${orgs}, ${reviews}`,
  publicProfileReviewsFewSub: (reviews: string) => `Мало отзывов · ${reviews}`,
  publicProfileWorksRow: 'Работы',
  publicProfileWorksCount: (photos: string) => `Работы · ${photos}`,
  publicProfileSpecializationCaption: 'Специализация',
  publicProfileCategoriesRow: 'Категории',
  publicProfileAreasRow: 'Районы',
  publicProfileBrandsRow: 'Бренды',
  publicProfileDescriptionCaption: 'О себе',
  publicProfileGalleryPhotoAlt: (index: number) => `Работа исполнителя, фото ${index}`,
  reviewsHeader: 'Отзывы',
  reviewsSummary: (orgs: string, reviews: string) => `${orgs} · ${reviews}`,
  reviewsFewTitle: 'Мало отзывов',
  reviewsFewHint: 'Средняя оценка появится, когда отзывы оставят хотя бы 3 разные организации.',
  reviewsAuthorStars: (author: string, stars: string) => `${author} · ${stars}`,
  reviewsReplyRow: 'Ответить на отзыв',
  reviewsReplyTitle: 'Ответ на отзыв',
  reviewsReplyLabel: 'Ответ',
  reviewsAppealTitle: 'Оспорить отзыв',
  reviewsActionsLabel: (author: string) => `Действия с отзывом: ${author}`,

  portfolioTitle: 'Галерея работ',
  portfolioHint: 'Фото проходят модерацию, прежде чем попасть в публичный профиль',
  portfolioUpload: 'Добавить фото',
  portfolioUploading: 'Загружаем…',
  portfolioUploadError: 'Не удалось загрузить фото',
  portfolioDelete: 'Удалить',
  portfolioEmpty: 'В галерее пока нет фотографий',
  portfolioLimitReached: 'Достигнут лимит фотографий в галерее',
  portfolioStateQuarantined: 'Проверяется',
  portfolioStateRejected: 'Отклонено',
  portfolioStateReady: 'Готово',
  registrationTitle: 'Регистрация',
  stepOf: (step: number, total: number) => `Шаг ${step} из ${total}`,
  next: 'Далее',
  fillProfile: 'Заполнить профиль',
  typeStepTitle: 'Кем вы работаете?',
  typeStepText: 'Проверка займёт 1–3 рабочих дня. До неё заявки не приходят.',
  typeCompanyHint: 'ООО, несколько мастеров',
  typeSelfEmployedHint: 'Проверим статус НПД',
  nameLabel: 'Название',
  categoriesCaption: 'Что ремонтируете',
  areasCaption: 'Районы',
  representativeTitle: 'Подтвердим, что вы представляете компанию',
  representativeText:
    'Оператор позвонит по номеру из официального источника, а не по введённому здесь.',
  representativeNote: 'Сканы, печати и селфи не нужны.',
  kindCompany: 'Компания',
  kindIp: 'ИП',
  kindSelfEmployed: 'Самозанятый',
  draftHeroTitle: 'Профиль не отправлен',
  pendingHeroTitle: 'Профиль на проверке',
  pendingHeroText: (date: string) =>
    `Отправлено ${date}. Обычно проверка занимает 1–3 рабочих дня.`,
  needsInfoTitle: 'Нужны уточнения',
  informationAnswerLabel: 'Ответ оператору',
  informationAnswerPlaceholder: 'Например: удобно звонить в будни, 10:00–13:00',
  informationSend: 'Отправить',
  verificationDocumentsRow: 'Проверка и документы',
  suspendedTitle: 'Профиль приостановлен',
  suspendedText: 'Новые заявки не приходят.',
  rejectedTitle: 'Профиль отклонён',
  reasonText: (reason: string) => `Причина: ${reason}`,
  keptNotice: 'Текущие заявки и отзывы сохранены.',
  decisionDetails: 'Подробнее о решении',
  appealAction: 'Обжаловать',
  appealAgain: 'Обжаловать снова',
  appealSheetTitle: 'Обжаловать решение',
  appealSheetText:
    'Опишите, почему решение стоит пересмотреть. Обжалование рассмотрит оператор платформы.',
  appealTextLabel: 'Основания',
  appealTextPlaceholder: 'Например: неявки были по вине заказчика — есть переписка',
  appealSend: 'Отправить обжалование',
  appealPendingTitle: 'Обжалование на рассмотрении',
  appealPendingText: (date: string) => `Подано ${date}. Решение оператора появится здесь.`,
  appealUpheldTitle: 'Обжалование удовлетворено',
  appealDeclinedTitle: 'Обжалование отклонено',
  requisitesRow: 'Реквизиты и специализация',
  categoriesCount: (n: number) => (n === 0 ? 'Категории не выбраны' : `Категорий: ${n}`),
  notFilled: 'Не заполнено',
  staffRow: 'Сотрудники',
  integrationRow: 'Интеграция с CRM',
  portfolioScreenTitle: 'Портфолио',
  portfolioWorksTitle: 'Работы',
  portfolioHintLimit: (limit: number) => `До ${limit} фото. Каждое проверяет модератор.`,
  portfolioCount: (count: number, limit: number) => `${count} из ${limit}`,
  portfolioAddTile: 'Добавить',
  portfolioOpen: (index: number) => `Открыть работу ${index}`,
  portfolioRejectedNote: (reason: string) => `«Отклонено»: ${reason}`,
  portfolioRejectedDefault: 'фото не прошло модерацию.',
  portfolioCaptionLabel: 'Подпись к фото',
  portfolioCaptionPlaceholder: 'Например: замена компрессора витрины',
  portfolioCaptionHint: 'До 200 символов. Новая подпись проходит модерацию вместе с фото.',
  portfolioCaptionSave: 'Сохранить подпись',
  portfolioCaptionError: 'Не удалось сохранить подпись',
  portfolioOnModeration: 'На модерации',

  publicProfileAreasText: (city: string, districts: string[]) =>
    districts.length === 1
      ? `${city}, ${districts[0]}`
      : `${city}, ${districts.slice(0, -1).join(', ')} и ${districts[districts.length - 1]}`,
  ratingForms: ['оценка', 'оценки', 'оценок'] as const,
  customerForms: ['заказчик', 'заказчика', 'заказчиков'] as const,
  areaForms: ['район работы', 'района работы', 'районов работы'] as const,
  publicProfileChecksTitle: 'Проверки',
  publicProfileBrandsCheck: 'Работает с брендами',
  publicProfileBrandsStated: 'Со слов исполнителя, производители не подтверждали',
  publicProfileGalleryAll: (count: number) => `Все ${count}`,
  publicProfileGalleryLess: 'Свернуть',
  publicProfileReviewsAll: (count: number) => `Все ${count}`,
  reviewPreviewMeta: (rating: number, date: string) => `★ ${rating} · ${date}`,
  publicProfilePick: 'Выбрать исполнителем',

  openPublicProfile: 'Открыть',
  acceptingOnSub: 'Заявки приходят в MAX',
  acceptingPausedSub: 'Пауза. Текущие заявки остаются в работе',
  categoriesCaptionSettings: 'Что ремонтирую',
  areasCaptionSettings: 'Где работаю',
  areasCaptionCity: (city: string) => `Где работаю · ${city}`,
  areasWholeCity: 'Весь город',
  areasWholeCityHint:
    'Районы не выбраны — вы работаете по всему городу. Отметьте районы, чтобы сузить зону.',
  districtForms: ['район', 'района', 'районов'] as const,

  reviewRequestMeta: (number: string) => `заявка ${number}`,
  reviewReplyFrom: (organization: string) => `Ответ ${organization}`,
  reviewComplaintOpen: 'Пожаловаться на отзыв',
  reviewComplaintReasonTitle: 'Причина жалобы',
  reviewComplaintDetails: 'Подробности (необязательно)',
  reviewComplaintSend: 'Отправить',
  reviewComplaintPending: 'Жалоба на проверке',
  reviewComplaintSteps: {
    sent: 'Жалоба отправлена',
    check: 'Проверяет оператор',
    checkTime: 'до 2 дней',
    decision: 'Решение',
  },
  reviewComplaintVisibleNote:
    'Пока идёт проверка, отзыв остаётся в профиле. Решение оператора придёт в уведомлении.',
} as const;

export const workspace = {
  hubTitle: 'Заявки',
  hubSegmentsLabel: 'Какие заявки показать',
  chatsTitle: 'Чаты',
  chatsEmpty: 'Переписок пока нет',
  chatsEmptyText: 'Здесь появятся переписки по заявкам: вопросы заказчиков и ваши ответы.',
  chatsMine: (text: string) => `Вы: ${text}`,
  chatsBeforeChoice: 'до выбора',
  chatsPartialError: 'Часть переписок не загрузилась — откройте их из карточки заявки.',
  incomingTitle: 'Входящие',
  incomingEmpty: 'Входящих обращений пока нет',
  incomingDeadline: 'Подтвердите до',
  incomingDeadlineExpired: 'Срок подтверждения истёк',
  incomingHiddenContacts: 'Адрес и контакты появятся после подтверждения назначения',
  incomingAccept: 'Принять',
  incomingDecline: 'Отклонить',
  incomingDeclineReasonLabel: 'Причина отказа',
  incomingAskQuestion: 'Задать вопрос',

  inWorkTitle: 'В работе',
  inWorkEmpty: 'Принятых заявок пока нет',

  availableTitle: 'Доступные заявки',
  availableEmpty: 'Подходящих заявок пока нет',
  availableEmptyReasonsTitle: 'Возможные причины',
  availableEmptyProfileNotActive: 'Профиль ещё не допущен платформой (статус не «Допущен»)',
  availableEmptyNotAccepting: 'В профиле отключён приём новых заявок',
  availableEmptyNoMatch: 'В радиусе обслуживания и выбранных категориях сейчас нет заявок',
  availableMyOfferBadge: 'Есть ваш отклик',
  availableUrgency: 'Срочность',
  availableDistrict: 'Район',

  cardCategoryLabel: 'Категория',
  cardModelLabel: 'Модель',
  cardDescriptionLabel: 'Описание',
  cardPhotosLabel: 'Опубликованные фото',
  cardPublishedAt: 'Опубликовано',
  cardSearchExpires: 'Поиск закрывается',
  cardMyOffersTitle: 'Ваши отклики',
  cardNoOffers: 'Вы ещё не откликались на эту заявку',
  cardNotInSearch: 'Заявка больше не в поиске.',

  priceModeLabel: 'Стоимость',
  priceModeAmount: 'Сумма',
  priceModeUnknown: 'Требует уточнения',
  priceModeFree: 'Бесплатно',
  priceAmountLabel: 'Сумма, ₽',
  priceZeroReasonLabel: 'Основание (почему бесплатно)',
  vatModeLabel: 'НДС',
  vatModeOption: {
    included: 'Включён в сумму',
    excluded: 'Не включён',
    not_applicable: 'Не облагается',
  },

  offerFormTitle: 'Ваше предложение',
  offerWindowStartLabel: 'Когда приедете, с',
  offerWindowEndLabel: 'До',
  offerTimezoneHint: 'Время указывается в часовом поясе города заявки',
  offerScopeLabel: 'Что входит',
  offerCommentLabel: 'Комментарий',
  offerAccessRequirementsLabel: 'Требования к доступу',
  offerValidUntilLabel: 'Действует до',
  offerSubmit: 'Отправить предложение',
  offerSubmitError: 'Не удалось отправить предложение',
  offerWithdraw: 'Отозвать',
  offerWithdrawConfirm: 'Отозвать это предложение?',
  offerWithdrawError: 'Не удалось отозвать предложение',
  offerStateLabel: 'Статус отклика',

  questionThreadTitle: 'Вопрос заказчику',
  questionPlaceholder: 'Ваш вопрос',
  questionSend: 'Отправить',

  detailAddressTitle: 'Адрес и контакты',
  detailAddressHiddenNotice:
    'Адрес и контакты появятся после подтверждения заявки.',
  detailAssignmentStatus: 'Состояние назначения',
  detailAcceptedNotice: 'Назначение принято — адрес и контакты доступны ниже',

  actionProposeVisit: 'Предложить выезд',
  actionChangeVisit: 'Изменить условия выезда',
  actionChangeVisitWarning:
    'Изменение уже согласованных условий вернёт заявку на повторное согласование заказчику',
  visitProposalStatusLabel: 'Согласование выезда',
  visitProposalNotApproved: 'Не согласовано',
  visitProposalFormTitle: 'Условия выезда',

  actionCreateRepairQuote: 'Смета ремонта',
  repairQuoteFormTitle: 'Смета ремонта',
  repairQuoteDescriptionLabel: 'Описание работ',
  repairQuoteStatusLabel: 'Согласование сметы',
  repairQuoteNotApproved: 'Не согласовано',
  repairQuoteSubmit: 'Отправить смету',

  warrantyTitle: 'Решение о гарантийности',
  warrantyDisclaimer:
    'Укажите, покрывает ли гарантия этот ремонт, и поясните решение заказчику.',
  warrantyCommentLabel: 'Пояснение решения (обязательно)',
  warrantyOption: {
    not_stated: 'Не указано',
    warranty: 'Гарантийный случай',
    not_warranty: 'Не гарантийный случай',
    undetermined: 'Пока не определено',
  },
  warrantySave: 'Сохранить решение',

  fieldWorkerTitle: 'Выездной мастер',
  fieldWorkerModeStaff: 'Сотрудник организации',
  fieldWorkerModeExternal: 'Имя и телефон',
  fieldWorkerStaffLabel: 'Сотрудник',
  fieldWorkerNameLabel: 'Имя',
  fieldWorkerPhoneLabel: 'Телефон',
  fieldWorkerStatedByCompany: 'Приглашённый мастер',
  fieldWorkerSave: 'Назначить',

  actionStartWork: 'Начать работу',
  actionStartWorkDisabledNotice: 'Отметить «На месте» можно после согласования выезда',

  reportCompletionTitle: 'Сообщить о результате',
  reportOutcomeLabel: 'Исход',
  reportOutcomeOption: {
    resolved: 'Устранено',
    not_resolved: 'Не устранено',
  },
  reportSummaryLabel: 'Описание выполненного',
  reportSubmit: 'Отправить',

  cancellationRespondTitle: 'Ответ на запрос отмены',
  cancellationAgree: 'Согласен',
  cancellationDisagree: 'Не согласен',
  cancellationCommentLabel: 'Комментарий',
  cancellationSubmit: 'Отправить ответ',

  actionWithdrawAssignment: 'Отказаться от заявки',
  withdrawReasonLabel: 'Причина отказа',
  withdrawConfirm:
    'Отказаться от принятой заявки? Заказчик увидит это как отказ и сможет выбрать другого исполнителя.',

  attachmentsUploadTitle: 'Прикрепить фото',
  genericActionError: 'Не удалось выполнить действие',

  detailNotFound: 'Заявка не найдена или недоступна.',
  detailAssignmentEnded:
    'Назначение по этой заявке прекращено — содержимое заявки больше недоступно.',
  detailUrgencyLabel: 'Срочность',
  detailAddressLabel: 'Адрес',
  detailContactLabel: 'Контакт',
  cancellationStatusLabel: 'Статус',
  cancellationReasonLabel: 'Причина заказчика',
  rowSubtitle: (...parts: (string | null | undefined)[]) => parts.filter(Boolean).join(' · '),
  orgSubtitle: (organization: string, role: string) => `${organization} · ${role}`,
  incomingNewTag: 'Новая',
  incomingEmptyText: 'Когда заказчик направит заявку вашей компании, она появится здесь.',
  incomingReplyUntil: 'Ответить до',
  incomingRefuse: 'Отказаться',
  incomingRefuseSheetTitle: 'Отказаться от заявки?',
  incomingRefuseSheetText: 'Заказчик увидит причину и сможет направить заявку другому исполнителю.',
  incomingDeclineReasonPlaceholder: 'Например: нет мастера нужного профиля',
  inWorkEmptyText: 'Принятые заявки появятся здесь.',
  inWorkTag: {
    accepted: 'Согласуйте выезд',
    scheduled: 'Выезд согласован',
    in_progress: 'Идёт работа',
    completion_reported: 'Ждём подтверждения',
    action_required: 'Нужно действие',
    cancellation_pending: 'Запрос отмены',
    closed: 'Закрыта',
    cancelled: 'Отменена',
  },
  availableShortTitle: 'Доступные',
  availableSubtitle: 'Заявки в ваших районах и категориях',
  availableContactsNote: 'Точный адрес и контакты откроются, если заказчик выберет вас.',
  noOffersTag: 'Нет предложений',
  clarificationTag: 'Уточнение',
  waitingAnswerNote: 'ждёт ответа на вопрос',
  answeredNote: 'заказчик ответил',
  replyUntil: (time: string) => `ответить до ${time}`,
  urgentNote: 'срочно',
  contractRow: 'Договор',
  contractNumber: (number: string) => `№ ${number}`,
  askQuestionRow: 'Задать вопрос',
  askQuestionTitle: 'Вопрос заказчику',
  askQuestionSubtitle: (number: string) => `${number} · до выбора`,
  askQuestionBannerTitle: 'Видите только вы и заказчик',
  askQuestionBannerText: 'Адрес и телефон откроются, если заказчик выберет вас.',
  offerScreenTitle: 'Предложение',
  offerPriceLabel: 'Стоимость выезда и диагностики',
  offerScopePlaceholder: 'Например: выезд, диагностика до 1 часа',
  offerValidUntilScreenLabel: 'Предложение действует до',
  offerTimezoneHintWith: (timezone: string | null | undefined) =>
    timezone ? `Время — в часовом поясе заявки (${timezone})` : 'Время — в часовом поясе заявки',
  extraCaption: 'Дополнительно',
  priceAmountPlaceholder: '0 ₽',
  priceUnknownSwitch: 'Назову после осмотра',
  priceFreeSwitch: 'Бесплатно, 0 ₽',
  vatModeNotSet: 'Не указан',
  sendForApproval: 'Отправить на согласование',
  visitRow: 'Выезд',
  agreedRow: 'Согласовано',
  warrantyRow: 'Гарантия',
  detailLocationLabel: 'Точка',
  detailContactRow: 'Контакт на месте',
  fieldWorkerNone: 'Не назначен',
  fieldWorkerStaffPlaceholder: 'Выберите сотрудника',
  fieldWorkerExternalNote:
    'Имя и телефон мастера будут видны заказчику.',
  actionChangeTime: 'Изменить время выезда',
  actionRepairQuote: 'Предложить цену ремонта',
  quotePendingHint: 'Смета ждёт ответа заказчика',
  changeTermsNote: 'Изменение времени или цены отправит заказчику новую версию на согласование.',
  messagesRow: 'Переписка',
  detailsRow: 'Описание и фото',
  serialLabel: 'Серийный номер',
  photoAddLabel: 'Добавить',
  providerStatusNote: {
    completion_reported: 'Заявку закроет заказчик, когда подтвердит результат.',
    action_required: 'Заказчик решает, как продолжить заявку.',
    closed: 'Работа по заявке завершена.',
    cancelled: 'Заявка отменена заказчиком.',
  },
  quoteLinesLabel: 'Позиции сметы',
  quoteScreenTitle: 'Стоимость ремонта',
  quoteNoteLabel: 'Комментарий к смете',
  quoteAddLine: 'Добавить позицию',
  quoteLineEditTitle: 'Позиция сметы',
  quoteLineEdit: (title: string) => `Изменить позицию: ${title}`,
  quoteLineTitleLabel: 'Работа или деталь',
  quoteLineTitlePlaceholder: 'Например: пусковое реле',
  quoteLineAdd: 'Добавить',
  quoteLineRemove: 'Удалить позицию',
  quoteLineAmountWarrantyHint: 'При гарантийном ремонте сумма для заказчика — 0 ₽',
  quoteTotalCaption: 'Итого для заказчика',
  quoteWarrantySwitch: 'Гарантийный ремонт, 0 ₽',
  quoteWarrantyReasonPlaceholder: 'Например: гарантия производителя, договор № …',
  quoteNotePlaceholder: 'Что ещё важно знать заказчику',
  quoteApprovedTag: 'Ремонт согласован',
  quoteStatusTag: {
    pending: 'Не согласовано',
    approved: 'Ремонт согласован',
    rejected: 'Отклонена',
    expired: 'Срок истёк',
    superseded: 'Заменена',
  },
  reportScreenTitle: 'Отчёт о работе',
  reportHeader: 'Отчёт',
  reportWhatDone: 'Что сделано',
  reportSummaryPlaceholder: 'Например: заменил пусковое реле, проверил давление',
  reportPhotosCaption: 'Фото до и после',
  reportPhotoAdd: (slot: string) => `Добавить фото «${slot}»`,
  reportCloseNote: 'Заявку закроет заказчик, когда подтвердит результат.',
  reportSend: 'Отправить заказчику',
  cancellationBannerTitle: {
    cancel_request: 'Заказчик просит отменить заявку',
    change_provider: 'Заказчик просит сменить исполнителя',
  },
  cancellationBannerText: (reason: string | null | undefined) =>
    `${reason ? `Причина: «${reason}». ` : ''}После подтверждения доступ к заявке закроется.`,
  cancellationReasonText: (reason: string) => `Причина: «${reason}».`,
  cancellationConfirm: 'Подтвердить отмену',
  cancellationConfirmTitle: 'Подтвердить отмену?',
  cancellationConfirmText: 'Доступ к заявке закроется.',
  cancellationDisagreeTitle: 'Не согласны с отменой?',
  cancellationDisagreeText:
    'Объясните заказчику, почему. Комментарий увидит и оператор, если возникнет спор.',
  withdrawSheetTitle: 'Отказаться от принятой заявки?',

  acceptingOn: 'Принимаю',
  acceptingPaused: 'Пауза',
  jobsEmpty: 'Заявок пока нет',
  jobsEmptyText:
    'Когда заказчик выберет вас или появится подходящая заявка, пришлём уведомление в MAX.',
  pausedEmptyText: 'Вы на паузе. Новые заявки не приходят, пока вы не включите приём.',
  pausedNoteTitle: 'Вы на паузе',
  pausedNoteText: 'Новые заявки не приходят. Входящие и заявки в работе остаются у вас.',
  jobUrgencyTag: urgencyText as Record<string, string>,
  contractNumberMeta: (number: string) => `По договору № ${number}`,

  detailHeader: (customer: string | null | undefined, number: string) =>
    customer ? `${customer} · ${number}` : number,
  workStepsLabel: 'Ход работ',
  workSteps: {
    enRoute: 'Выехал',
    visitAgreed: 'Выезд согласован',
    onSite: 'На месте',
    diagnostics: 'Диагностика',
    quoteAgreed: 'Цена ремонта согласована',
    completed: 'Работа завершена',
  },
  phaseTitle: {
    'propose-visit': 'Согласуйте выезд',
    'visit-pending': 'Ждём согласования выезда',
    scheduled: 'Выезд согласован',
    enRoute: 'В пути',
    diagnostics: 'Диагностика',
    'quote-pending': 'Ждём согласования',
    repair: 'Ремонт',
    completion: 'Ждём приёмки',
    decision: 'Решает заказчик',
    cancellation: 'Запрос отмены',
    closed: 'Заявка закрыта',
    cancelled: 'Заявка отменена',
  } as Record<string, string>,
  phaseText: {
    'propose-visit': 'Предложите время и стоимость выезда — заказчик согласует их в MAX.',
    'visit-pending': 'Заказчик получил условия выезда. Когда согласует, здесь появится время.',
    'quote-pending': 'Заказчик получил цену ремонта. Когда согласует, можно начинать ремонт.',
    completion: 'Заявку закроет заказчик, когда подтвердит результат.',
    decision: 'Заказчик решает, как продолжить заявку.',
    closed: 'Работа по заявке завершена.',
    cancelled: 'Заявка отменена заказчиком.',
  } as Record<string, string>,
  quoteRejectedText: (comment: string | null | undefined) =>
    comment ? `Заказчик отклонил цену ремонта: «${comment}».` : 'Заказчик отклонил цену ремонта.',
  actionEnRoute: 'Я выехал',
  actionOnSite: 'Я на месте',
  actionWorkDone: 'Работа завершена',
  quoteCardTitle: 'Предложение по ремонту',
  quoteCardTotal: 'Итого',

  urgencyEyebrow: {
    critical: 'СРОЧНО · СЕГОДНЯ',
    urgent: 'СРОЧНО · 1–2 ДНЯ',
    normal: 'НЕ СРОЧНО',
  } as Record<string, string>,
  cardPublishedLine: (when: string) => `Опубликовано ${when}`,
  cardSearchUntil: (when: string) => `поиск до ${when}`,
  offerWhenTitle: 'Когда приедете',
  slotToday: (time: string) => `Сегодня ${time}`,
  slotTomorrow: (time: string) => `Завтра ${time}`,
  slotCustom: 'Другое время',
  slotWindowNote: (timezone: string | null | undefined) =>
    timezone
      ? `Окно выезда — 2 часа, время заявки (${timezone}).`
      : 'Окно выезда — 2 часа, время заявки.',
  offerVisitPriceTitle: 'Выезд и диагностика',
  offerRepairLater: 'Стоимость ремонта предложите после диагностики.',
  offerTermsRow: 'Условия предложения',
  offerTermsHint: 'Что входит, срок действия, доступ',
  offerRespond: 'Откликнуться',
  offerSentLine: (price: string) => `Отклик отправлен · ${price}`,
  priceDecrease: 'Меньше на 100 ₽',
  priceIncrease: 'Больше на 100 ₽',
} as const;
