import { roleShort } from './onboarding';

export const urgencyText = {
  critical: 'Сегодня',
  urgent: '1–3 дня',
  normal: 'Не срочно',
} as const;

export const home = {
  myService: 'Мой сервис',
  findProvider: 'Найти исполнителя',
  activeRequests: 'Активные обращения',
  routeTabsLabel: 'Маршрут обращения',

  needDecision: 'Нужно ваше решение',
  inWork: 'В работе',
  drafts: 'Черновики',
  emptyTitle: 'Активных заявок нет',
  emptyText: 'Здесь появятся заявки, которые ждут вашего решения.',
  emptyEmployeeText: 'Здесь появятся ваши заявки и черновики.',
  roleShort,
  draftSaved: (when: string) => `Сохранён ${when}`,
  decisionVisit: (price: string | null) => (price ? `Выезд ${price}` : 'Выезд'),
  decisionQuote: (price: string | null) => (price ? `Смета ${price}` : 'Смета ремонта'),
  decisionOfferForms: ['предложение', 'предложения', 'предложений'] as const,
  decisionRespondBy: (when: string) => `ответить до ${when}`,
  decisionToday: 'сегодня',
  decisionTomorrow: 'завтра',
  approvalTag: {
    draft_approval: 'Проверьте и опубликуйте',
    visit_proposal: 'Согласуйте выезд',
    repair_quote: 'Согласуйте ремонт',
    offers: 'Выберите исполнителя',
    completion_reported: 'Проверьте результат',
    cancellation_disputed: 'Ответ по отмене',
    action_required: 'Нужно решение',
    question: 'Вопрос мастера',
  },
  needAnswer: 'Нужен ваш ответ',
  questionFallback: 'Мастер задал вопрос',

  heading: 'Главная',
  pointLabel: 'Точка',
  allPoints: 'Все точки',
  pointPickerTitle: 'Какую точку показать',
  pointChange: (name: string) => `Точка: ${name}. Сменить`,
  nowInWork: 'Сейчас в работе',
  equipmentTitle: 'Техника',
  equipmentAll: (n: number) => `Все ${n}`,
  newRequest: 'Новая заявка',
  describeProblem: 'Описать проблему',
  findTitle: 'Найдём мастера, если свой сервис не может',
  findText: 'Опишите поломку. Проверенные исполнители пришлют время и цену, вы выберете.',
  findTextEmployee:
    'Опишите поломку. Руководитель проверит заявку и откроет поиск, исполнители пришлют время и цену.',
  providersNearby: 'Исполнителей в вашем районе',
  providersNone: 'В районе точки пока нет исполнителей',
  providersNoneText: 'Отправьте заявку своему сервису на вкладке «Мой сервис» — или загляните позже.',
  pickPointTitle: 'Выберите точку',
  pickPointText: 'Исполнители работают по районам — выберите точку, чтобы увидеть, кто рядом.',
  pickPoint: 'Выбрать точку',
  searching: 'Заявки в поиске',
  loadError: 'Не удалось загрузить главную',
} as const;

export const requests = {
  title: 'Заявки',
  newRequest: 'Новая заявка',
  requestNumber: 'Заявка №',
  unavailable: 'Заявка недоступна.',
  unavailableTitle: 'Заявка недоступна',
  unavailableDescription:
    'Возможно, у вас нет доступа к её точке или выбрана другая организация.',
  requestAccess: 'Запросить доступ',
  accessRequested: 'Запрос отправлен',
  accessRequestedText: 'Руководитель организации получит уведомление и сможет добавить вам точки.',
  toMyRequests: 'К моим заявкам',
  locationsCustomerOnly: 'Точки есть только у организаций-заказчиков.',
  equipmentCustomerOnly: 'Оборудование ведут организации-заказчики по своим точкам.',
  equipmentNeedsLocation: 'Сначала добавьте точку в разделе «Точки».',
  notFound: 'Заявка не найдена или недоступна.',
  providerSideHint: 'Откройте заявку из раздела «Входящие» или «В работе».',
  categoryShort: {
    'Холодильная витрина': 'Витрина',
    'Сплит-система холодильной камеры': 'Морозильная камера',
    'Холодильное оборудование': 'Холодильник',
    Кофемашины: 'Кофемашина',
  } as Record<string, string>,

  listScopeLabel: 'Какие заявки показать',
  scopeActive: 'Активные',
  scopeActiveCount: (n: number) => `Активные · ${n}`,
  scopeDone: 'Завершённые',
  filtersLabel: 'Фильтры',
  noResultsTitle: 'Нет заявок с такими фильтрами',
  noResultsText: 'Попробуйте другую точку или статус.',
  resetFilters: 'Сбросить фильтры',
  emptyTitle: 'Заявок пока нет',
  emptyText: 'Когда что-то сломается, создайте заявку — здесь будет видно, что с ней происходит.',
  doneEmptyTitle: 'Завершённых заявок нет',
  rowSubtitle: (number: string, location: string | null | undefined) =>
    location ? `${number} · ${location}` : number,
  tag: {
    draft: 'Черновик',
    approval_required: 'Ждёт руководителя',
    approval_required_manager: 'Проверьте и опубликуйте',
    awaiting_provider: 'Ждём ответа сервиса',
    searching: 'Ищем исполнителя',
    awaiting_assignment_confirmation: 'Ждём подтверждения',
    accepted: 'Ждём условий выезда',
    scheduled: 'Выезд согласован',
    in_progress: 'Мастер работает',
    completion_reported: 'Работа завершена',
    completion_reported_manager: 'Проверьте результат',
    action_required: 'Ждёт руководителя',
    action_required_manager: 'Нужно решение',
    cancellation_pending: 'Запрошена отмена',
    closed: 'Закрыта',
    cancelled: 'Отменена',
  },

  filtersTitle: 'Фильтры',
  filterLocation: 'Точка',
  filterAllLocations: 'Все точки',
  filterStatus: 'Статус',
  filterAllStatuses: 'Все статусы',
  filterActiveOnly: 'Только активные',
  filterIncludeClosed: 'Показать и завершённые',
  empty: 'Заявок пока нет',
  emptyFiltered: 'По заданным фильтрам заявок нет',
  loadMore: 'Показать ещё',
  pointsLabel: 'Точка',
  pointEmptyTitle: 'На этой точке заявок нет',
  pointEmptyText: 'Выберите другую точку или создайте заявку',
  dayToday: 'сегодня',
  dayYesterday: 'вчера',
  enRoute: 'Мастер едет',
  doneRated: (rating: number) => `Выполнено · ★ ${rating}`,
  unreadMessages: (n: number) => `Непрочитанных сообщений: ${n}`,
  listError: 'Не удалось загрузить список заявок',

  routePicker: {
    title: 'Новая заявка',
    pickTitle: 'Что сломалось?',
    equipmentLabel: 'Техника',
    noLocationsTitle: 'Точек пока нет',
    noLocations: 'Сначала добавьте точку и оборудование.',
    noEquipmentTitle: 'Техники пока нет',
    noEquipmentText: 'Добавьте технику на точке — тогда по ней можно будет создать заявку.',
    addEquipment: 'Добавить технику',
    equipmentMissing: 'Техники нет в списке',
    equipmentSubtitle: (location: string | null | undefined, service: string | null) =>
      [location, service].filter(Boolean).join(' · '),
    routeTitle: 'Кому отправить',
    ownServiceSubtitle: {
      service_contract: 'Ваш сервис по договору · напрямую',
      warranty: 'Ваш гарантийный сервис · напрямую',
      preferred: 'Ваш постоянный сервис · напрямую',
    } as Record<string, string>,
    ownServiceNoneTitle: 'Свой сервис не привязан',
    ownServiceNoneHint: 'Привяжите сервис в карточке техники',
    contactTitle: (name: string) => `Мой контакт: ${name}`,
    contactHint: (phone: string | null | undefined) =>
      phone
        ? `Заявку через приложение не доставить — позвоните: ${phone}`
        : 'Заявку через приложение не доставить — свяжитесь с мастером напрямую',
    pickEquipmentFirst: 'Сначала выберите технику',
    marketplaceTitle: 'Найти исполнителя',
    marketplaceDescription: 'Предложения от проверенных мастеров',
    marketplaceDescriptionEmployee: 'Вы подготовите заявку, руководитель проверит и опубликует',
    next: 'Далее',
  },
  routeLabel: {
    own_service: 'Свой сервис',
    marketplace: 'Внешний поиск',
  },

  wizard: {
    routeTitle: {
      own_service: 'Мой сервис',
      marketplace: 'Найти исполнителя',
    },
    stepOf: (n: number, total: number) => `Шаг ${n} из ${total}`,
    next: 'Далее',

    basisWarranty: 'Гарантийное обслуживание',
    basisContract: 'Обслуживание по договору',
    basisContractNumber: (number: string) => `Обслуживание по договору № ${number}`,
    basisPreferred: 'Постоянный сервис организации',

    changeEquipment: 'Изменить технику',
    changeEquipmentTitle: 'Техника в заявке',
    changeEquipmentDone: 'Готово',
    selectLocationLabel: 'Точка',
    selectEquipmentLabel: 'Оборудование',
    noEquipment: 'На этой точке пока нет оборудования',
    ownServiceMissing: 'Для этой техники сервис не подключён',
    ownServiceMissingHint:
      'Своему сервису заявку не отправить. Найдите исполнителя в новой заявке или подключите сервис в разделе «Техника».',

    detailsTitle: 'Что случилось?',
    symptomsGroupLabel: 'Что происходит с техникой',
    symptomPresets: {
      commercial_display_fridge: ['Не держит холод', 'Иней', 'Шумит', 'Течёт', 'Не включается'],
      refrigerator_cabinet: ['Не держит холод', 'Иней', 'Шумит', 'Течёт', 'Не включается'],
      chest_freezer: ['Не морозит', 'Иней', 'Шумит', 'Не закрывается', 'Не включается'],
      split_system_cold_room: ['Не держит холод', 'Обмерзает', 'Шумит', 'Течёт', 'Ошибка на пульте'],
      refrigeration_unit: ['Не держит холод', 'Шумит', 'Течёт', 'Часто включается', 'Не включается'],
      bar_fridge: ['Не держит холод', 'Иней', 'Шумит', 'Течёт', 'Не включается'],
      ice_maker: ['Не делает лёд', 'Мало льда', 'Течёт', 'Шумит', 'Не включается'],
      fridge: ['Не держит холод', 'Иней', 'Шумит', 'Течёт', 'Не включается'],
      coffee: ['Не греет', 'Течёт', 'Шумит', 'Ошибка на экране', 'Не включается'],
    } as Record<string, readonly string[]>,
    symptomPresetsDefault: ['Не включается', 'Шумит', 'Течёт', 'Ошибка на экране'],
    symptomsLabel: 'Подробнее',
    symptomsPlaceholder: 'Что произошло, как проявляется',
    errorCodeLabel: 'Код ошибки',
    errorCodePlaceholder: 'Если есть, например E1',
    urgencyLabel: 'Когда нужен мастер',
    urgencyOption: urgencyText,
    urgencyShort: urgencyText,
    draftSaving: 'Сохраняем черновик…',
    draftSavedAt: (time: string) => `Черновик сохранён · ${time}`,
    draftSaveError: 'Черновик не сохранён — проверьте соединение',
    offlineNotice: 'Нет сети. Изменения не сохранены — они останутся только на этом экране.',

    photosTitle: 'Фото',
    photosHint:
      'По ним мастер поймёт, какие запчасти взять. JPEG, PNG, WebP, до 10 МБ, не больше 10 фото.',
    photoAlt: (slotLabel: string, index: number) => `${slotLabel}, фото ${index}`,
    photoOpen: (alt: string) => `${alt}: заменить или удалить`,
    photoAdd: (slotLabel: string) => `Добавить фото: ${slotLabel}`,
    photoRetry: (slotLabel: string) => `Выбрать другое фото: ${slotLabel}`,
    photoSizeLabel: (slotLabel: string, megabytes: number) => `${slotLabel} · ${megabytes} МБ`,
    photoUploading: 'Загружаем…',
    photoTooLarge: (slotLabel: string) =>
      `${slotLabel}: файл больше 10 МБ. Снимите заново или выберите другой — остальное сохранено.`,
    photoUploadFailed: (slotLabel: string) =>
      `${slotLabel}: фото не загрузилось. Попробуйте ещё раз — остальное сохранено.`,
    photoRejected: (slots: string) => `Не прошли проверку: ${slots}. Снимите заново.`,
    photoLimit: 'Больше 10 фото к заявке не приложить.',
    photoReplace: 'Заменить фото',
    photoRemove: 'Удалить фото',
    noScreen: 'На технике нет экрана',
    cannotPhoto: 'Не могу сделать фото',

    noPhotoTitle: 'Почему нет фото?',
    noPhotoHint: 'Мастер увидит причину. Срочную заявку можно отправить и без фото.',
    noPhotoReasons: ['Техника в закрытом помещении', 'Нет времени, срочно', 'Камера не работает'],
    noPhotoOther: 'Другое',
    noPhotoOtherLabel: 'Причина',
    noPhotoOtherPlaceholder: 'Например: техника в недоступном месте',
    noPhotoNext: 'Далее',
    noPhotoReasonRequired: 'Выберите причину — мастер увидит её в заявке.',
    descriptionRequired: 'Опишите, что случилось: выберите признак или напишите пару слов.',
    returnedTitle: 'Заявку вернули на доработку',
    returnedText: (comment: string, by: string | null) => (by ? `«${comment}» — ${by}` : `«${comment}»`),

    photosIncompleteTitle: 'Не хватает обязательных фото',
    photosIncompleteNotice:
      'Обычную заявку так не отправить — добавьте фото или укажите, почему их нет.',
    photosIncompleteUrgentNotice:
      'Заявка срочная — её можно отправить с пометкой о неполных данных.',
    photosIncompleteConfirm: 'Отправить с пометкой о неполных данных',

    reviewTitle: 'Всё верно?',
    reviewRecipient: 'Кому',
    reviewProblem: 'Проблема',
    reviewWhen: 'Когда',
    reviewEdit: 'Изменить',
    reviewEditLabel: (label: string, value: string) => `${label}: ${value}. Изменить`,
    reviewRecipientOwn: (name: string, basis: string) => `${name}, ${basis}`,
    reviewRecipientBasis: {
      service_contract: 'по договору',
      warranty: 'гарантийный сервис',
      preferred: 'постоянный сервис',
    } as Record<string, string>,
    reviewRecipientMarketplace: 'Найти исполнителя',
    reviewRecipientApproval: 'Найти исполнителя, опубликует руководитель',
    reviewEquipmentValue: (equipment: string, location: string | null | undefined) =>
      location ? `${equipment}, ${location}` : equipment,
    reviewBasisWarranty: 'Гарантийное обслуживание подтверждено',
    reviewBasisContract: 'Обслуживание по договору подтверждено',
    reviewBasisPreferred: 'Обслуживание подтверждено',
    reviewApprovalTitle: 'Опубликует руководитель',
    reviewApprovalText: (approver: string | null | undefined) =>
      `${approver?.trim() || 'Руководитель'} проверит, что увидят исполнители, и откроет поиск.`,
    reviewMarketplaceTitle: 'Поиск исполнителя',
    reviewMarketplaceText:
      'Перед публикацией вы увидите, что узнают мастера. До выбора они не увидят адрес.',
    reviewEquipment: 'Техника',
    reviewUrgency: 'Срочность',
    reviewErrorCode: 'Код ошибки',
    reviewPhotos: 'Фото',
    reviewPhotosCount: (filled: number, total: number) => `${filled} из ${total}`,
    reviewNoSymptoms: 'Описание не заполнено',
    reviewNoPhotoReason: (reason: string) => `Без фото: ${reason}`,
    reviewOnlyProvider: (name: string) =>
      `Заявку увидят только сотрудники сервиса ${name}. Если сервис не ответит, предложим найти другого исполнителя.`,

    submitOwnService: 'Отправить заявку',
    submitApproval: 'Отправить руководителю',
    submitPublish: 'Далее: что увидят исполнители',
    submitError: 'Не удалось отправить заявку',
    serviceBindingRequiredError:
      'Для этой техники нет подтверждённого сервиса — создайте заявку с поиском исполнителя',

    offlineTitle: 'Нет соединения',
    offlineText: (time: string) =>
      `Заявка не отправлена. Черновик сохранён на сервере в ${time}. Изменения после этого остались на телефоне.`,
    offlineRetry: 'Повторить отправку',
    offlineBot: 'Продолжить в чате с ботом',

    cancelDraft: 'Отменить черновик',
    cancelDraftConfirm: 'Отменить черновик заявки? Действие нельзя отменить.',

    draftCard: {
      title: 'Черновик',
      savedOnServer: (when: string) => `сохранён на сервере ${when}`,
      bannerTitle: 'Заявка ещё не отправлена',
      bannerText: 'Никто её не видит. Продолжить можно здесь или в чате с ботом.',
      description: 'Описание',
      descriptionEmpty: 'не заполнено',
      photos: 'Фото',
      photosNone: 'не добавлены',
      recipient: 'Получатель',
      recipientNone: 'не выбран',
      continue: 'Продолжить заполнение',
      delete: 'Удалить черновик',
      deleteConfirm: 'Удалить черновик?',
      deleteConfirmText: 'Черновик пропадёт и здесь, и в чате с ботом. Действие нельзя отменить.',
      deleteConfirmButton: 'Удалить',
      deleteError: 'Не удалось удалить черновик',
    },

    sent: {
      title: 'Заявка отправлена',
      text: (number: string, provider: string | null) =>
        provider ? `${number} · ${provider}. Статус пришлём в чат MAX.` : `${number}. Статус пришлём в чат MAX.`,
      approvalTitle: 'Заявка отправлена руководителю',
      approvalText: (number: string) =>
        `${number}. Руководитель проверит, что увидят исполнители, и откроет поиск. Статус пришлём в чат MAX.`,
      open: 'Открыть заявку',
    },
  },

  status: {
    draft: 'Черновик',
    approval_required: 'Ждёт решения руководителя',
    awaiting_provider: 'Отправлено сервису',
    searching: 'Идёт поиск исполнителя',
    awaiting_assignment_confirmation: 'Ждём подтверждения исполнителя',
    accepted: 'Принято исполнителем',
    scheduled: 'Выезд согласован',
    in_progress: 'Исполнитель работает',
    completion_reported: 'Исполнитель сообщил о результате',
    closed: 'Закрыта',
    action_required: 'Нужно решение',
    cancellation_pending: 'Запрошена отмена',
    cancelled: 'Отменена',
  },
  statusWhatNext: {
    draft: 'Заявка не отправлена — продолжите заполнение или отправьте её.',
    approval_required: 'Ждём решения руководителя: опубликовать во внешнем поиске, отправить своему сервису или вернуть на доработку.',
    awaiting_provider: 'Ждём ответа от своего сервиса — принятия или отказа.',
    searching: 'Ждём предложений от исполнителей внешнего поиска.',
    awaiting_assignment_confirmation: 'Исполнитель выбран — ждём его подтверждения.',
    accepted: 'Исполнитель принял заявку — ждём согласования времени и стоимости выезда.',
    scheduled: 'Выезд согласован — ждём начала работ.',
    in_progress: 'Исполнитель работает над заявкой.',
    completion_reported: 'Ждём вашего подтверждения результата.',
    closed: 'Заявка закрыта.',
    action_required: 'Нужно ваше решение: новый маршрут, повторная публикация или отмена.',
    cancellation_pending: 'Ждём ответа исполнителя на запрос отмены.',
    cancelled: 'Заявка отменена.',
  },
  urgency: urgencyText,
  assignmentState: {
    pending: 'Ждём ответа исполнителя',
    accepted: 'Принято исполнителем',
    declined: 'Отклонено исполнителем',
    expired: 'Срок ответа истёк',
    revoked: 'Отозвано вами',
    withdrawn: 'Исполнитель отказался от работы',
    completed: 'Работа завершена',
  },
  deliveryDistinct: {
    delivered: 'Доставлено',
    accepted: 'Принято',
    scheduled: 'Выезд согласован',
  },

  photosTemplateNote: 'Шаблон фото зависит от категории оборудования',

  publish: {
    title: 'Что увидят исполнители',
    previewTitle: 'Публичная карточка',
    shownFields: 'Будет видно',
    hiddenFields: 'Останется скрытым',
    hiddenFieldLabel: {
      'location.address': 'Точный адрес',
      'location.name': 'Название точки',
      'location.contact_name': 'Контактное лицо',
      'location.contact_phone': 'Телефон точки',
      'equipment.serial_number': 'Серийный номер',
      'equipment.notes': 'Примечания по оборудованию',
      warranty_documents: 'Гарантийные документы',
      service_history: 'История обслуживания',
    },
    descriptionLabel: 'Описание для исполнителей',
    descriptionPlaceholder: 'Опишите неисправность своими словами — категорию, модель и район исполнитель увидит отдельно',
    districtLabel: 'Район (для внешнего поиска)',
    photosLabel: 'Фото для публикации',
    photosHint: 'По умолчанию ничего чувствительного не выбрано. Фото шильдика и документов — только с явным подтверждением.',
    sensitivePhotoWarning: 'Это фото помечено как чувствительное (шильдик/документ) — подтвердите публикацию отдельно',
    confirmSensitiveLabel: 'Публикую чувствительное фото осознанно',
    existingBindingTitle: 'Уже есть привязанный сервис',
    existingBindingDescription: 'У оборудования есть привязка своего сервиса — публикация во внешний поиск не отменяет её.',
    matchedProviders: 'Подходящих исполнителей',
    matchedProvidersZero: 'Подходящих исполнителей не найдено',
    matchedProvidersHint: 'Оценка по категории и территории на момент публикации',
    publishButton: 'Опубликовать',
    publishError: 'Не удалось опубликовать заявку',
    publishedTitle: 'Заявка опубликована',
    publishedDescription: 'Ждём предложений от исполнителей внешнего поиска',

    noProvidersTitle: 'Нет подходящих исполнителей',
    noProvidersDescription: 'По категории и району подходящих исполнителей сейчас нет. Можно изменить условия, повторить попытку позже или отменить заявку.',
    changeConditions: 'Изменить условия',
    retrySearch: 'Повторить поиск',
    cancelSearch: 'Отменить заявку',

    previewCaption: 'Так увидят исполнители',
    previewEquipment: 'Техника',
    previewDistrict: 'Район',
    previewUrgency: 'Срочность',
    previewDescription: 'Описание',
    previewPhotos: 'Фото',
    previewPhotosCount: (n: number) => (n === 0 ? 'без фото' : `${n} шт.`),
    previewCityOnly: (city: string) => `${city}, весь город`,
    screenTitle: 'Найти исполнителя',
    subtitle: 'Адрес и телефон откроются только выбранному мастеру.',
    equipmentRow: 'Техника',
    districtPlaceholder: 'Весь город',
    photoSensitiveSubtitle: 'На фото серийный номер',
    photoFallback: (n: number) => `Фото ${n}`,
    noPhotos: 'К заявке нет готовых фото.',
    sensitiveBannerTitle: 'Шильдик попадёт в публикацию',
    sensitiveBannerText: 'На фото может быть серийный номер. Подтвердите, что публикуете его осознанно.',
    notPublished: (list: string) => `Не публикуются: ${list}.`,
    matchedCount: (n: number) => `Подходящих исполнителей: ${n}`,
    bindingTitle: 'У этой техники есть сервис',
    bindingText: (equipment: string, provider: string) =>
      `${equipment} обслуживает ${provider}. Внешний ремонт может повлиять на гарантию.`,
    bindingNote: 'Решение о гарантии принимает сервис, приложение его не проверяет.',
    searchAnyway: 'Всё равно искать',
    sendTo: (provider: string) => `Отправить в ${provider}`,
    ownServiceFallback: 'свой сервис',
  },
} as const;
