export const reviews = {
  sectionTitle: 'Отзыв о ремонте',
  notAllowedNoAssignment: 'Отзыв доступен только по заявке с принятым назначением исполнителя.',
  notAllowedCancelledBeforeWork:
    'Заявка отменена до начала работ — звёзд за ремонт здесь не бывает. Если дело в неявке или недобросовестном отказе исполнителя — подайте жалобу на взаимодействие.',
  complainAboutInteraction: 'Пожаловаться на неявку',
  needsAdmission: 'Решение о допуске отзыва примет модератор — работы начались, но заявка не была штатно завершена.',

  ratingLabel: 'Оценка',
  textLabel: 'Текст отзыва',
  textPlaceholder: 'Что понравилось, что нет — по существу выполненной работы',
  textLimitHint: 'До 4000 символов',
  showNameLabel: 'Показывать название организации',
  showNameHint: 'Если выключено, в отзыве будет указано «Подтверждённый бизнес-клиент» — без названия компании',
  photosLabel: 'Фото для публикации в отзыве',
  photosHint:
    'Отдельно от фото заявки: по умолчанию ничего не выбрано, выберите сами, что показать в отзыве. Ничего не публикуется автоматически.',
  photosEmpty: 'К заявке не приложено ни одной фотографии',
  sensitivePhotoWarning: 'Это фото помечено как чувствительное (шильдик/документ) — подтвердите публикацию отдельно',
  confirmSensitiveLabel: 'На фото может быть серийный номер — опубликовать?',
  photosSensitiveBlockedHint: 'Без подтверждения это фото не попадёт в отправку',

  submit: 'Отправить отзыв',
  submitEdit: 'Сохранить правку',
  submitError: 'Не удалось отправить отзыв',

  moderationPending: 'Отзыв на модерации',
  moderationPendingDescription: 'После проверки отзыв станет виден исполнителю и в его публичном профиле.',
  moderationPublished: 'Отзыв опубликован',
  moderationRejected: 'Отзыв отклонён',
  moderationRemoved: 'Отзыв удалён модератором',
  moderationReasonLabel: 'Причина',

  editButton: 'Изменить отзыв',
  editNotice: 'Правка снова пройдёт модерацию. Пока решение не принято, виден прежний опубликованный текст. Новая оценка не создаётся — оценка входит в общий рейтинг только после публикации версии.',
  publishedVersionLabel: 'Опубликовано сейчас',

  appealButton: 'Обжаловать решение',
  appealReasonLabel: 'Причина обжалования',
  appealSubmit: 'Отправить обжалование',
  appealSent: 'Обжалование отправлено — рассмотрит оператор',
  appealError: 'Не удалось отправить обжалование',

  replyTitle: 'Ответ исполнителя',
  replyNone: 'Исполнитель ещё не ответил',

  screenHeader: 'Отзыв',
  screenTitle: (provider: string) => `Как поработал ${provider}?`,
  screenTitleGeneric: 'Как поработал исполнитель?',
  screenSubtitle: (number: string, equipment: string) => `Заявка ${number} · ${equipment}`,
  fieldLabel: 'Отзыв',
  showNameHintShort: 'Иначе — «Подтверждённый бизнес-клиент»',
  photosRow: 'Фото к отзыву',
  photosRowHint: 'Выберите отдельно, фото заявки не публикуются сами',
  photosSelected: (count: number) => `Выбрано фото: ${count}`,
  photosDone: 'Готово',
  photoSensitiveTag: 'Шильдик',
  submitForReview: 'Отправить на проверку',
  rejectedTitle: 'Отзыв не опубликован',
  rejectedFallback: 'Исправьте отзыв и отправьте снова или обжалуйте решение.',
  statusRow: 'Статус',
  statusTag: {
    pending: 'На проверке',
    published: 'Опубликован',
    rejected: 'На исправлении',
    removed: 'Удалён',
  } as Record<string, string>,
  ratingValue: (rating: number) => `★ ${rating}`,
  fixButton: 'Исправить отзыв',
  appealShort: 'Обжаловать',
  appealTitle: 'Обжалование решения',
  cardRowLeave: 'Оцените работу исполнителя',

  formTitle: 'Как прошёл ремонт?',
  formPlaceholder: 'Что понравилось, что можно улучшить',
  photosSection: 'Фото в отзыв',
  photosSectionHint: 'Отмеченные увидят все. Остальные останутся в заявке.',
  showCompanyLabel: 'Показывать название компании',
  thanksTitle: 'Спасибо!',
  thanksText: 'Отзыв появится в профиле после проверки. Обычно это занимает до суток.',
} as const;

export const complaints = {
  subjectLabel: {
    provider_profile: 'Жалоба на профиль исполнителя',
    review: 'Жалоба на отзыв',
    attachment: 'Жалоба на фотографию',
    no_show: 'Жалоба на неявку',
  },
  button: {
    provider_profile: 'Пожаловаться на исполнителя',
    review: 'Пожаловаться на отзыв',
    attachment: 'Пожаловаться',
    no_show: 'Жалоба на неявку',
  },
  descriptionLabel: 'Опишите, что произошло',
  descriptionPlaceholder: 'Как можно подробнее — это поможет оператору разобраться',
  submit: 'Отправить жалобу',
  submitError: 'Не удалось отправить жалобу',
  sent: 'Жалоба отправлена',
  noShowRequiresVisit: 'Жалоба на неявку доступна только после согласованного выезда',

  myTitle: 'Мои жалобы',
  empty: 'Жалоб пока нет',
  loadMore: 'Показать ещё',
  status: {
    pending: 'На рассмотрении',
    published: 'Подтверждена',
    rejected: 'Отклонена',
    removed: 'Удовлетворена',
    withdrawn: 'Отозвана',
  },
  decisionReasonLabel: 'Решение оператора',
  appealStatusLabel: 'Статус обжалования',

  sheetTitle: 'На что жалуетесь?',
  listCaption: 'Поданные жалобы',
  typesLabel: 'Тип жалобы',
  typeLabel: {
    no_show: 'Мастер не приехал',
    provider_profile: 'Профиль или фото',
    attachment: 'Фото',
    review: 'Отзыв',
  },
  reviewSubject: (author: string, date: string) => `Отзыв · ${author} · ${date}`,
  whatHappened: 'Что случилось',
  operatorNote: 'Жалобу рассмотрит оператор. Решение и причина придут в уведомлении.',
  send: 'Отправить',
  emptyText: 'Здесь будут жалобы на неявку, профиль, фото и отзывы — со статусом и решением оператора.',
  appealLine: (status: string) => `Обжалование: ${status}`,
  reasonCode: {
    not_our_work: 'Отзыв не о нашей работе',
    abuse_or_personal_data: 'Оскорбления или личные данные',
    customer_not_involved: 'Заказчик не был на заявке',
    other: 'Другое',
  },
  withdraw: 'Отозвать жалобу',
  withdrawConfirm: 'Отозвать жалобу? Оператор не будет её рассматривать, отзыв останется как есть.',
  withdrawConfirmLabel: 'Отозвать',
  withdrawError: 'Не удалось отозвать жалобу',
  withdrawnNote: 'Жалоба отозвана. При необходимости можно подать новую.',
} as const;
